// ISO 3166-1 alpha-2 → Russian name and the Latin slug used in the URL.
//
// Data, not copy: a country's name and its conventional Latin spelling are
// facts, and the generator needs both so it never has to invent either the
// heading on a page or the address of one. A country absent from this table
// simply gets no page — silently guessing a transliteration would produce a
// URL nobody can link to and search engines would treat as a soft 404.
export const COUNTRY_NAMES = Object.freeze({
  AD: { ru: "Андорра", slug: "andorra" },
  AE: { ru: "ОАЭ", slug: "uae" },
  AF: { ru: "Афганистан", slug: "afghanistan" },
  AG: { ru: "Антигуа и Барбуда", slug: "antigua-and-barbuda" },
  AI: { ru: "Ангилья", slug: "anguilla" },
  AL: { ru: "Албания", slug: "albania" },
  AM: { ru: "Армения", slug: "armenia" },
  AO: { ru: "Ангола", slug: "angola" },
  AR: { ru: "Аргентина", slug: "argentina" },
  AS: { ru: "Американское Самоа", slug: "american-samoa" },
  AT: { ru: "Австрия", slug: "austria" },
  AU: { ru: "Австралия", slug: "australia" },
  AW: { ru: "Аруба", slug: "aruba" },
  AX: { ru: "Аландские острова", slug: "aland-islands" },
  AZ: { ru: "Азербайджан", slug: "azerbaijan" },
  BA: { ru: "Босния и Герцеговина", slug: "bosnia-and-herzegovina" },
  BB: { ru: "Барбадос", slug: "barbados" },
  BD: { ru: "Бангладеш", slug: "bangladesh" },
  BE: { ru: "Бельгия", slug: "belgium" },
  BF: { ru: "Буркина-Фасо", slug: "burkina-faso" },
  BG: { ru: "Болгария", slug: "bulgaria" },
  BH: { ru: "Бахрейн", slug: "bahrain" },
  BI: { ru: "Бурунди", slug: "burundi" },
  BJ: { ru: "Бенин", slug: "benin" },
  BL: { ru: "Сен-Бартелеми", slug: "saint-barthelemy" },
  BM: { ru: "Бермуды", slug: "bermuda" },
  BN: { ru: "Бруней", slug: "brunei" },
  BO: { ru: "Боливия", slug: "bolivia" },
  BQ: { ru: "Бонайре", slug: "bonaire" },
  BR: { ru: "Бразилия", slug: "brazil" },
  BS: { ru: "Багамы", slug: "bahamas" },
  BT: { ru: "Бутан", slug: "bhutan" },
  BW: { ru: "Ботсвана", slug: "botswana" },
  BY: { ru: "Беларусь", slug: "belarus" },
  BZ: { ru: "Белиз", slug: "belize" },
  CA: { ru: "Канада", slug: "canada" },
  CD: { ru: "ДР Конго", slug: "dr-congo" },
  CF: { ru: "ЦАР", slug: "central-african-republic" },
  CG: { ru: "Конго", slug: "congo" },
  CH: { ru: "Швейцария", slug: "switzerland" },
  CI: { ru: "Кот-д’Ивуар", slug: "ivory-coast" },
  CK: { ru: "Острова Кука", slug: "cook-islands" },
  CL: { ru: "Чили", slug: "chile" },
  CM: { ru: "Камерун", slug: "cameroon" },
  CN: { ru: "Китай", slug: "china" },
  CO: { ru: "Колумбия", slug: "colombia" },
  CR: { ru: "Коста-Рика", slug: "costa-rica" },
  CU: { ru: "Куба", slug: "cuba" },
  CV: { ru: "Кабо-Верде", slug: "cape-verde" },
  CW: { ru: "Кюрасао", slug: "curacao" },
  CY: { ru: "Кипр", slug: "cyprus" },
  CZ: { ru: "Чехия", slug: "czechia" },
  DE: { ru: "Германия", slug: "germany" },
  DJ: { ru: "Джибути", slug: "djibouti" },
  DK: { ru: "Дания", slug: "denmark" },
  DM: { ru: "Доминика", slug: "dominica" },
  DO: { ru: "Доминикана", slug: "dominican-republic" },
  DZ: { ru: "Алжир", slug: "algeria" },
  EC: { ru: "Эквадор", slug: "ecuador" },
  EE: { ru: "Эстония", slug: "estonia" },
  EG: { ru: "Египет", slug: "egypt" },
  ER: { ru: "Эритрея", slug: "eritrea" },
  ES: { ru: "Испания", slug: "spain" },
  ET: { ru: "Эфиопия", slug: "ethiopia" },
  FI: { ru: "Финляндия", slug: "finland" },
  FJ: { ru: "Фиджи", slug: "fiji" },
  FK: { ru: "Фолклендские острова", slug: "falkland-islands" },
  FM: { ru: "Микронезия", slug: "micronesia" },
  FO: { ru: "Фарерские острова", slug: "faroe-islands" },
  FR: { ru: "Франция", slug: "france" },
  GA: { ru: "Габон", slug: "gabon" },
  GB: { ru: "Великобритания", slug: "united-kingdom" },
  GD: { ru: "Гренада", slug: "grenada" },
  GE: { ru: "Грузия", slug: "georgia" },
  GF: { ru: "Французская Гвиана", slug: "french-guiana" },
  GG: { ru: "Гернси", slug: "guernsey" },
  GH: { ru: "Гана", slug: "ghana" },
  GI: { ru: "Гибралтар", slug: "gibraltar" },
  GL: { ru: "Гренландия", slug: "greenland" },
  GM: { ru: "Гамбия", slug: "gambia" },
  GN: { ru: "Гвинея", slug: "guinea" },
  GP: { ru: "Гваделупа", slug: "guadeloupe" },
  GQ: { ru: "Экваториальная Гвинея", slug: "equatorial-guinea" },
  GR: { ru: "Греция", slug: "greece" },
  GT: { ru: "Гватемала", slug: "guatemala" },
  GU: { ru: "Гуам", slug: "guam" },
  GW: { ru: "Гвинея-Бисау", slug: "guinea-bissau" },
  GY: { ru: "Гайана", slug: "guyana" },
  HK: { ru: "Гонконг", slug: "hong-kong" },
  HN: { ru: "Гондурас", slug: "honduras" },
  HR: { ru: "Хорватия", slug: "croatia" },
  HT: { ru: "Гаити", slug: "haiti" },
  HU: { ru: "Венгрия", slug: "hungary" },
  ID: { ru: "Индонезия", slug: "indonesia" },
  IE: { ru: "Ирландия", slug: "ireland" },
  IL: { ru: "Израиль", slug: "israel" },
  IM: { ru: "Остров Мэн", slug: "isle-of-man" },
  IN: { ru: "Индия", slug: "india" },
  IQ: { ru: "Ирак", slug: "iraq" },
  IR: { ru: "Иран", slug: "iran" },
  IS: { ru: "Исландия", slug: "iceland" },
  IT: { ru: "Италия", slug: "italy" },
  JE: { ru: "Джерси", slug: "jersey" },
  JM: { ru: "Ямайка", slug: "jamaica" },
  JO: { ru: "Иордания", slug: "jordan" },
  JP: { ru: "Япония", slug: "japan" },
  KE: { ru: "Кения", slug: "kenya" },
  KG: { ru: "Киргизия", slug: "kyrgyzstan" },
  KH: { ru: "Камбоджа", slug: "cambodia" },
  KI: { ru: "Кирибати", slug: "kiribati" },
  KM: { ru: "Коморы", slug: "comoros" },
  KN: { ru: "Сент-Китс и Невис", slug: "saint-kitts-and-nevis" },
  KR: { ru: "Южная Корея", slug: "south-korea" },
  KW: { ru: "Кувейт", slug: "kuwait" },
  KY: { ru: "Каймановы острова", slug: "cayman-islands" },
  KZ: { ru: "Казахстан", slug: "kazakhstan" },
  LA: { ru: "Лаос", slug: "laos" },
  LB: { ru: "Ливан", slug: "lebanon" },
  LC: { ru: "Сент-Люсия", slug: "saint-lucia" },
  LI: { ru: "Лихтенштейн", slug: "liechtenstein" },
  LK: { ru: "Шри-Ланка", slug: "sri-lanka" },
  LR: { ru: "Либерия", slug: "liberia" },
  LS: { ru: "Лесото", slug: "lesotho" },
  LT: { ru: "Литва", slug: "lithuania" },
  LU: { ru: "Люксембург", slug: "luxembourg" },
  LV: { ru: "Латвия", slug: "latvia" },
  LY: { ru: "Ливия", slug: "libya" },
  MA: { ru: "Марокко", slug: "morocco" },
  MC: { ru: "Монако", slug: "monaco" },
  MD: { ru: "Молдова", slug: "moldova" },
  ME: { ru: "Черногория", slug: "montenegro" },
  MF: { ru: "Сен-Мартен", slug: "saint-martin" },
  MG: { ru: "Мадагаскар", slug: "madagascar" },
  MH: { ru: "Маршалловы Острова", slug: "marshall-islands" },
  MK: { ru: "Северная Македония", slug: "north-macedonia" },
  ML: { ru: "Мали", slug: "mali" },
  MM: { ru: "Мьянма", slug: "myanmar" },
  MN: { ru: "Монголия", slug: "mongolia" },
  MO: { ru: "Макао", slug: "macau" },
  MP: { ru: "Северные Марианские острова", slug: "northern-mariana-islands" },
  MQ: { ru: "Мартиника", slug: "martinique" },
  MR: { ru: "Мавритания", slug: "mauritania" },
  MS: { ru: "Монтсеррат", slug: "montserrat" },
  MT: { ru: "Мальта", slug: "malta" },
  MU: { ru: "Маврикий", slug: "mauritius" },
  MV: { ru: "Мальдивы", slug: "maldives" },
  MW: { ru: "Малави", slug: "malawi" },
  MX: { ru: "Мексика", slug: "mexico" },
  MY: { ru: "Малайзия", slug: "malaysia" },
  MZ: { ru: "Мозамбик", slug: "mozambique" },
  NA: { ru: "Намибия", slug: "namibia" },
  NC: { ru: "Новая Каледония", slug: "new-caledonia" },
  NE: { ru: "Нигер", slug: "niger" },
  NG: { ru: "Нигерия", slug: "nigeria" },
  NI: { ru: "Никарагуа", slug: "nicaragua" },
  NL: { ru: "Нидерланды", slug: "netherlands" },
  NO: { ru: "Норвегия", slug: "norway" },
  NP: { ru: "Непал", slug: "nepal" },
  NR: { ru: "Науру", slug: "nauru" },
  NU: { ru: "Ниуэ", slug: "niue" },
  NZ: { ru: "Новая Зеландия", slug: "new-zealand" },
  OM: { ru: "Оман", slug: "oman" },
  PA: { ru: "Панама", slug: "panama" },
  PE: { ru: "Перу", slug: "peru" },
  PF: { ru: "Французская Полинезия", slug: "french-polynesia" },
  PG: { ru: "Папуа — Новая Гвинея", slug: "papua-new-guinea" },
  PH: { ru: "Филиппины", slug: "philippines" },
  PK: { ru: "Пакистан", slug: "pakistan" },
  PL: { ru: "Польша", slug: "poland" },
  PM: { ru: "Сен-Пьер и Микелон", slug: "saint-pierre-and-miquelon" },
  PR: { ru: "Пуэрто-Рико", slug: "puerto-rico" },
  PS: { ru: "Палестина", slug: "palestine" },
  PT: { ru: "Португалия", slug: "portugal" },
  PW: { ru: "Палау", slug: "palau" },
  PY: { ru: "Парагвай", slug: "paraguay" },
  QA: { ru: "Катар", slug: "qatar" },
  RE: { ru: "Реюньон", slug: "reunion" },
  RO: { ru: "Румыния", slug: "romania" },
  RS: { ru: "Сербия", slug: "serbia" },
  RU: { ru: "Россия", slug: "russia" },
  RW: { ru: "Руанда", slug: "rwanda" },
  SA: { ru: "Саудовская Аравия", slug: "saudi-arabia" },
  SB: { ru: "Соломоновы Острова", slug: "solomon-islands" },
  SC: { ru: "Сейшелы", slug: "seychelles" },
  SD: { ru: "Судан", slug: "sudan" },
  SE: { ru: "Швеция", slug: "sweden" },
  SG: { ru: "Сингапур", slug: "singapore" },
  SI: { ru: "Словения", slug: "slovenia" },
  SK: { ru: "Словакия", slug: "slovakia" },
  SL: { ru: "Сьерра-Леоне", slug: "sierra-leone" },
  SM: { ru: "Сан-Марино", slug: "san-marino" },
  SN: { ru: "Сенегал", slug: "senegal" },
  SO: { ru: "Сомали", slug: "somalia" },
  SR: { ru: "Суринам", slug: "suriname" },
  SS: { ru: "Южный Судан", slug: "south-sudan" },
  ST: { ru: "Сан-Томе и Принсипи", slug: "sao-tome-and-principe" },
  SV: { ru: "Сальвадор", slug: "el-salvador" },
  SX: { ru: "Синт-Мартен", slug: "sint-maarten" },
  SY: { ru: "Сирия", slug: "syria" },
  SZ: { ru: "Эсватини", slug: "eswatini" },
  TC: { ru: "Тёркс и Кайкос", slug: "turks-and-caicos" },
  TD: { ru: "Чад", slug: "chad" },
  TG: { ru: "Того", slug: "togo" },
  TH: { ru: "Таиланд", slug: "thailand" },
  TJ: { ru: "Таджикистан", slug: "tajikistan" },
  TL: { ru: "Восточный Тимор", slug: "timor-leste" },
  TM: { ru: "Туркменистан", slug: "turkmenistan" },
  TN: { ru: "Тунис", slug: "tunisia" },
  TO: { ru: "Тонга", slug: "tonga" },
  TR: { ru: "Турция", slug: "turkey" },
  TT: { ru: "Тринидад и Тобаго", slug: "trinidad-and-tobago" },
  TV: { ru: "Тувалу", slug: "tuvalu" },
  TW: { ru: "Тайвань", slug: "taiwan" },
  TZ: { ru: "Танзания", slug: "tanzania" },
  UA: { ru: "Украина", slug: "ukraine" },
  UG: { ru: "Уганда", slug: "uganda" },
  US: { ru: "США", slug: "usa" },
  UY: { ru: "Уругвай", slug: "uruguay" },
  VA: { ru: "Ватикан", slug: "vatican" },
  UZ: { ru: "Узбекистан", slug: "uzbekistan" },
  VC: { ru: "Сент-Винсент и Гренадины", slug: "saint-vincent-and-the-grenadines" },
  VE: { ru: "Венесуэла", slug: "venezuela" },
  VG: { ru: "Британские Виргинские острова", slug: "british-virgin-islands" },
  VI: { ru: "Американские Виргинские острова", slug: "us-virgin-islands" },
  VN: { ru: "Вьетнам", slug: "vietnam" },
  VU: { ru: "Вануату", slug: "vanuatu" },
  WS: { ru: "Самоа", slug: "samoa" },
  XK: { ru: "Косово", slug: "kosovo" },
  YE: { ru: "Йемен", slug: "yemen" },
  YT: { ru: "Майотта", slug: "mayotte" },
  ZA: { ru: "ЮАР", slug: "south-africa" },
  ZM: { ru: "Замбия", slug: "zambia" },
  ZW: { ru: "Зимбабве", slug: "zimbabwe" },
});

export const flagEmoji = (iso) => String(iso || '').toUpperCase().replace(/[A-Z]/g,
  (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));

