// Country identity for the storefront: slug, ISO, flag and the Russian name
// forms. Nothing else.
//
// UNTIL 2026-09-01 THIS FILE ALSO HELD PAGE TEXT — title, description, lead,
// intro, cards and FAQ for twenty-one countries — and a second generator,
// build-country-pages.mjs, built pages from it. That generator was never called
// by build-all.mjs, so those pages were regenerated by nobody and read by no
// editorial gate: content-review.mjs and test-editorial-dupes.mjs glob
// seo/content-profiles/*.json. The two copies had already drifted: a fix landed
// in esim/malaysia/index.html while the text here kept the defect.
//
// All of it now lives in seo/content-profiles/. The generator is deleted, and
// seo/test-one-pipeline.mjs fails if a second path ever appears. What is left
// here is a dictionary — the one thing profiles do not carry, because Russian
// case forms belong to the language, not to the editorial copy.
//
// build-guides.mjs reads slug, flagEmoji, nameRu and nameGen from ALL.
// build-catalogue-pages.mjs reads slug, to assert every editorial country has a
// profile. Nothing reads page text from here, and nothing should again.

export const SITE = 'https://magicesim.store';

// flagImg: existing PNG in assets/flags/ (null -> use flagEmoji instead).
export const COUNTRIES = [
  { slug: "indonesia", iso: "ID", flagImg: "id.png", flagEmoji: "🇮🇩", nameRu: "Индонезия", nameGen: "Индонезии", namePrep: "Индонезии", nameAcc: "Индонезию" },
  { slug: "japan", iso: "JP", flagImg: "jp.png", flagEmoji: "🇯🇵", nameRu: "Япония", nameGen: "Японии", namePrep: "Японии", nameAcc: "Японию" },
  { slug: "south-korea", iso: "KR", flagImg: "kr.png", flagEmoji: "🇰🇷", nameRu: "Южная Корея", nameGen: "Южной Кореи", namePrep: "Южной Корее", nameAcc: "Южную Корею" },
  { slug: "malaysia", iso: "MY", flagImg: null, flagEmoji: "🇲🇾", nameRu: "Малайзия", nameGen: "Малайзии", namePrep: "Малайзии", nameAcc: "Малайзию" },
  { slug: "singapore", iso: "SG", flagImg: null, flagEmoji: "🇸🇬", nameRu: "Сингапур", nameGen: "Сингапура", namePrep: "Сингапуре", nameAcc: "Сингапур" },
  { slug: "egypt", iso: "EG", flagImg: "eg.png", flagEmoji: "🇪🇬", nameRu: "Египет", nameGen: "Египта", namePrep: "Египте", nameAcc: "Египет" },
  { slug: "india", iso: "IN", flagImg: null, flagEmoji: "🇮🇳", nameRu: "Индия", nameGen: "Индии", namePrep: "Индии", nameAcc: "Индию" },
  { slug: "sri-lanka", iso: "LK", flagImg: "lk.png", flagEmoji: "🇱🇰", nameRu: "Шри-Ланка", nameGen: "Шри-Ланки", namePrep: "Шри-Ланке", nameAcc: "Шри-Ланку" },
  { slug: "maldives", iso: "MV", flagImg: "mv.png", flagEmoji: "🇲🇻", nameRu: "Мальдивы", nameGen: "Мальдив", namePrep: "Мальдивах", nameAcc: "Мальдивы" },
  { slug: "georgia", iso: "GE", flagImg: null, flagEmoji: "🇬🇪", nameRu: "Грузия", nameGen: "Грузии", namePrep: "Грузии", nameAcc: "Грузию" },
  { slug: "armenia", iso: "AM", flagImg: null, flagEmoji: "🇦🇲", nameRu: "Армения", nameGen: "Армении", namePrep: "Армении", nameAcc: "Армению" },
  { slug: "kazakhstan", iso: "KZ", flagImg: null, flagEmoji: "🇰🇿", nameRu: "Казахстан", nameGen: "Казахстана", namePrep: "Казахстане", nameAcc: "Казахстан" },
  { slug: "usa", iso: "US", flagImg: null, flagEmoji: "🇺🇸", nameRu: "США", nameGen: "США", namePrep: "США", nameAcc: "США" },
  { slug: "mexico", iso: "MX", flagImg: null, flagEmoji: "🇲🇽", nameRu: "Мексика", nameGen: "Мексики", namePrep: "Мексике", nameAcc: "Мексику" },
  { slug: "brazil", iso: "BR", flagImg: null, flagEmoji: "🇧🇷", nameRu: "Бразилия", nameGen: "Бразилии", namePrep: "Бразилии", nameAcc: "Бразилию" },
  { slug: "italy", iso: "IT", flagImg: "it.png", flagEmoji: "🇮🇹", nameRu: "Италия", nameGen: "Италии", namePrep: "Италии", nameAcc: "Италию" },
  { slug: "spain", iso: "ES", flagImg: "es.png", flagEmoji: "🇪🇸", nameRu: "Испания", nameGen: "Испании", namePrep: "Испании", nameAcc: "Испанию" },
  { slug: "france", iso: "FR", flagImg: "fr.png", flagEmoji: "🇫🇷", nameRu: "Франция", nameGen: "Франции", namePrep: "Франции", nameAcc: "Францию" },
  { slug: "germany", iso: "DE", flagImg: null, flagEmoji: "🇩🇪", nameRu: "Германия", nameGen: "Германии", namePrep: "Германии", nameAcc: "Германию" },
  { slug: "greece", iso: "GR", flagImg: "gr.png", flagEmoji: "🇬🇷", nameRu: "Греция", nameGen: "Греции", namePrep: "Греции", nameAcc: "Грецию" },
  { slug: "cyprus", iso: "CY", flagImg: "cy.png", flagEmoji: "🇨🇾", nameRu: "Кипр", nameGen: "Кипра", namePrep: "Кипре", nameAcc: "Кипр" },
];

// The five oldest pages. Kept separate only because the hub and related-links
// blocks have always ordered them first.
export const EXISTING = [
  { slug: "thailand", iso: "TH", flagImg: "th.png", flagEmoji: "🇹🇭", nameRu: "Таиланд", nameGen: "Таиланда" },
  { slug: "turkey", iso: "TR", flagImg: "tr.png", flagEmoji: "🇹🇷", nameRu: "Турция", nameGen: "Турции" },
  { slug: "china", iso: "CN", flagImg: "cn.png", flagEmoji: "🇨🇳", nameRu: "Китай", nameGen: "Китая" },
  { slug: "uae", iso: "AE", flagImg: "ae.png", flagEmoji: "🇦🇪", nameRu: "ОАЭ", nameGen: "ОАЭ" },
  { slug: "vietnam", iso: "VN", flagImg: "vn.png", flagEmoji: "🇻🇳", nameRu: "Вьетнам", nameGen: "Вьетнама" },
];

export const ALL = [...EXISTING, ...COUNTRIES];
