// ISO 3166-1 alpha-2 → Russian name and the Latin slug used in the URL.
//
// Data, not copy: a country's name and its conventional Latin spelling are
// facts, and the generator needs both so it never has to invent either the
// heading on a page or the address of one. A country absent from this table
// simply gets no page — silently guessing a transliteration would produce a
// URL nobody can link to and search engines would treat as a soft 404.
export const COUNTRY_NAMES = Object.freeze({
  AD: { ru: "Андорра", gen: "Андорры", en: "Andorra", slug: "andorra" },
  AE: { ru: "ОАЭ", gen: "ОАЭ", en: "United Arab Emirates", slug: "uae" },
  AF: { ru: "Афганистан", gen: "Афганистана", en: "Afghanistan", slug: "afghanistan" },
  AG: { ru: "Антигуа и Барбуда", gen: "Антигуа и Барбуды", en: "Antigua and Barbuda", slug: "antigua-and-barbuda" },
  AI: { ru: "Ангилья", gen: "Ангильи", en: "Anguilla", slug: "anguilla" },
  AN: { ru: 'Нидерландские Антильские острова', gen: "Нидерландских Антильских островов", en: "Netherlands Antilles", slug: 'netherlands-antilles' },
  AL: { ru: "Албания", gen: "Албании", en: "Albania", slug: "albania" },
  AM: { ru: "Армения", gen: "Армении", en: "Armenia", slug: "armenia" },
  AO: { ru: "Ангола", gen: "Анголы", en: "Angola", slug: "angola" },
  AR: { ru: "Аргентина", gen: "Аргентины", en: "Argentina", slug: "argentina" },
  AS: { ru: "Американское Самоа", gen: "Американского Самоа", en: "American Samoa", slug: "american-samoa" },
  AT: { ru: "Австрия", gen: "Австрии", en: "Austria", slug: "austria" },
  AU: { ru: "Австралия", gen: "Австралии", en: "Australia", slug: "australia" },
  AW: { ru: "Аруба", gen: "Арубы", en: "Aruba", slug: "aruba" },
  AX: { ru: "Аландские острова", gen: "Аландских островов", en: "Åland Islands", slug: "aland-islands" },
  AZ: { ru: "Азербайджан", gen: "Азербайджана", en: "Azerbaijan", slug: "azerbaijan" },
  BA: { ru: "Босния и Герцеговина", gen: "Боснии и Герцеговины", en: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina" },
  BB: { ru: "Барбадос", gen: "Барбадоса", en: "Barbados", slug: "barbados" },
  BD: { ru: "Бангладеш", gen: "Бангладеш", en: "Bangladesh", slug: "bangladesh" },
  BE: { ru: "Бельгия", gen: "Бельгии", en: "Belgium", slug: "belgium" },
  BF: { ru: "Буркина-Фасо", gen: "Буркина-Фасо", en: "Burkina Faso", slug: "burkina-faso" },
  BG: { ru: "Болгария", gen: "Болгарии", en: "Bulgaria", slug: "bulgaria" },
  BH: { ru: "Бахрейн", gen: "Бахрейна", en: "Bahrain", slug: "bahrain" },
  BI: { ru: "Бурунди", gen: "Бурунди", en: "Burundi", slug: "burundi" },
  BJ: { ru: "Бенин", gen: "Бенина", en: "Benin", slug: "benin" },
  BL: { ru: "Сен-Бартелеми", gen: "Сен-Бартелеми", en: "Saint Barthélemy", slug: "saint-barthelemy" },
  BM: { ru: "Бермуды", gen: "Бермуд", en: "Bermuda", slug: "bermuda" },
  BN: { ru: "Бруней", gen: "Брунея", en: "Brunei", slug: "brunei" },
  BO: { ru: "Боливия", gen: "Боливии", en: "Bolivia", slug: "bolivia" },
  BQ: { ru: "Бонайре", gen: "Бонайре", en: "Caribbean Netherlands", slug: "bonaire" },
  BR: { ru: "Бразилия", gen: "Бразилии", en: "Brazil", slug: "brazil" },
  BS: { ru: "Багамы", gen: "Багам", en: "Bahamas", slug: "bahamas" },
  BT: { ru: "Бутан", gen: "Бутана", en: "Bhutan", slug: "bhutan" },
  BW: { ru: "Ботсвана", gen: "Ботсваны", en: "Botswana", slug: "botswana" },
  BY: { ru: "Беларусь", gen: "Беларуси", en: "Belarus", slug: "belarus" },
  BZ: { ru: "Белиз", gen: "Белиза", en: "Belize", slug: "belize" },
  CA: { ru: "Канада", gen: "Канады", en: "Canada", slug: "canada" },
  CD: { ru: "ДР Конго", gen: "ДР Конго", en: "DR Congo", slug: "dr-congo" },
  CF: { ru: "ЦАР", gen: "ЦАР", en: "Central African Republic", slug: "central-african-republic" },
  CG: { ru: "Конго", gen: "Конго", en: "Republic of the Congo", slug: "congo" },
  CH: { ru: "Швейцария", gen: "Швейцарии", en: "Switzerland", slug: "switzerland" },
  CI: { ru: "Кот-д’Ивуар", gen: "Кот-д’Ивуара", en: "Côte d’Ivoire", slug: "ivory-coast" },
  CK: { ru: "Острова Кука", gen: "Островов Кука", en: "Cook Islands", slug: "cook-islands" },
  CL: { ru: "Чили", gen: "Чили", en: "Chile", slug: "chile" },
  CM: { ru: "Камерун", gen: "Камеруна", en: "Cameroon", slug: "cameroon" },
  CN: { ru: "Китай", gen: "Китая", en: "China", slug: "china" },
  CO: { ru: "Колумбия", gen: "Колумбии", en: "Colombia", slug: "colombia" },
  CR: { ru: "Коста-Рика", gen: "Коста-Рики", en: "Costa Rica", slug: "costa-rica" },
  CU: { ru: "Куба", gen: "Кубы", en: "Cuba", slug: "cuba" },
  CV: { ru: "Кабо-Верде", gen: "Кабо-Верде", en: "Cape Verde", slug: "cape-verde" },
  CW: { ru: "Кюрасао", gen: "Кюрасао", en: "Curaçao", slug: "curacao" },
  CY: { ru: "Кипр", gen: "Кипра", en: "Cyprus", slug: "cyprus" },
  CZ: { ru: "Чехия", gen: "Чехии", en: "Czechia", slug: "czechia" },
  DE: { ru: "Германия", gen: "Германии", en: "Germany", slug: "germany" },
  DJ: { ru: "Джибути", gen: "Джибути", en: "Djibouti", slug: "djibouti" },
  DK: { ru: "Дания", gen: "Дании", en: "Denmark", slug: "denmark" },
  DM: { ru: "Доминика", gen: "Доминики", en: "Dominica", slug: "dominica" },
  DO: { ru: "Доминикана", gen: "Доминиканы", en: "Dominican Republic", slug: "dominican-republic" },
  DZ: { ru: "Алжир", gen: "Алжира", en: "Algeria", slug: "algeria" },
  EC: { ru: "Эквадор", gen: "Эквадора", en: "Ecuador", slug: "ecuador" },
  EE: { ru: "Эстония", gen: "Эстонии", en: "Estonia", slug: "estonia" },
  EG: { ru: "Египет", gen: "Египта", en: "Egypt", slug: "egypt" },
  ER: { ru: "Эритрея", gen: "Эритреи", en: "Eritrea", slug: "eritrea" },
  ES: { ru: "Испания", gen: "Испании", en: "Spain", slug: "spain" },
  ET: { ru: "Эфиопия", gen: "Эфиопии", en: "Ethiopia", slug: "ethiopia" },
  FI: { ru: "Финляндия", gen: "Финляндии", en: "Finland", slug: "finland" },
  FJ: { ru: "Фиджи", gen: "Фиджи", en: "Fiji", slug: "fiji" },
  FK: { ru: "Фолклендские острова", gen: "Фолклендских островов", en: "Falkland Islands", slug: "falkland-islands" },
  FM: { ru: "Микронезия", gen: "Микронезии", en: "Micronesia", slug: "micronesia" },
  FO: { ru: "Фарерские острова", gen: "Фарерских островов", en: "Faroe Islands", slug: "faroe-islands" },
  FR: { ru: "Франция", gen: "Франции", en: "France", slug: "france" },
  GA: { ru: "Габон", gen: "Габона", en: "Gabon", slug: "gabon" },
  GB: { ru: "Великобритания", gen: "Великобритании", en: "United Kingdom", slug: "united-kingdom" },
  GD: { ru: "Гренада", gen: "Гренады", en: "Grenada", slug: "grenada" },
  GE: { ru: "Грузия", gen: "Грузии", en: "Georgia", slug: "georgia" },
  GF: { ru: "Французская Гвиана", gen: "Французской Гвианы", en: "French Guiana", slug: "french-guiana" },
  GG: { ru: "Гернси", gen: "Гернси", en: "Guernsey", slug: "guernsey" },
  GH: { ru: "Гана", gen: "Ганы", en: "Ghana", slug: "ghana" },
  GI: { ru: "Гибралтар", gen: "Гибралтара", en: "Gibraltar", slug: "gibraltar" },
  GL: { ru: "Гренландия", gen: "Гренландии", en: "Greenland", slug: "greenland" },
  GM: { ru: "Гамбия", gen: "Гамбии", en: "Gambia", slug: "gambia" },
  GN: { ru: "Гвинея", gen: "Гвинеи", en: "Guinea", slug: "guinea" },
  GP: { ru: "Гваделупа", gen: "Гваделупы", en: "Guadeloupe", slug: "guadeloupe" },
  GQ: { ru: "Экваториальная Гвинея", gen: "Экваториальной Гвинеи", en: "Equatorial Guinea", slug: "equatorial-guinea" },
  GR: { ru: "Греция", gen: "Греции", en: "Greece", slug: "greece" },
  GT: { ru: "Гватемала", gen: "Гватемалы", en: "Guatemala", slug: "guatemala" },
  GU: { ru: "Гуам", gen: "Гуама", en: "Guam", slug: "guam" },
  GW: { ru: "Гвинея-Бисау", gen: "Гвинеи-Бисау", en: "Guinea-Bissau", slug: "guinea-bissau" },
  GY: { ru: "Гайана", gen: "Гайаны", en: "Guyana", slug: "guyana" },
  HK: { ru: "Гонконг", gen: "Гонконга", en: "Hong Kong", slug: "hong-kong" },
  HN: { ru: "Гондурас", gen: "Гондураса", en: "Honduras", slug: "honduras" },
  HR: { ru: "Хорватия", gen: "Хорватии", en: "Croatia", slug: "croatia" },
  HT: { ru: "Гаити", gen: "Гаити", en: "Haiti", slug: "haiti" },
  HU: { ru: "Венгрия", gen: "Венгрии", en: "Hungary", slug: "hungary" },
  ID: { ru: "Индонезия", gen: "Индонезии", en: "Indonesia", slug: "indonesia" },
  IE: { ru: "Ирландия", gen: "Ирландии", en: "Ireland", slug: "ireland" },
  IL: { ru: "Израиль", gen: "Израиля", en: "Israel", slug: "israel" },
  IM: { ru: "Остров Мэн", gen: "Острова Мэн", en: "Isle of Man", slug: "isle-of-man" },
  IN: { ru: "Индия", gen: "Индии", en: "India", slug: "india" },
  IQ: { ru: "Ирак", gen: "Ирака", en: "Iraq", slug: "iraq" },
  IR: { ru: "Иран", gen: "Ирана", en: "Iran", slug: "iran" },
  IS: { ru: "Исландия", gen: "Исландии", en: "Iceland", slug: "iceland" },
  IT: { ru: "Италия", gen: "Италии", en: "Italy", slug: "italy" },
  JE: { ru: "Джерси", gen: "Джерси", en: "Jersey", slug: "jersey" },
  JM: { ru: "Ямайка", gen: "Ямайки", en: "Jamaica", slug: "jamaica" },
  JO: { ru: "Иордания", gen: "Иордании", en: "Jordan", slug: "jordan" },
  JP: { ru: "Япония", gen: "Японии", en: "Japan", slug: "japan" },
  KE: { ru: "Кения", gen: "Кении", en: "Kenya", slug: "kenya" },
  KG: { ru: "Киргизия", gen: "Киргизии", en: "Kyrgyzstan", slug: "kyrgyzstan" },
  KH: { ru: "Камбоджа", gen: "Камбоджи", en: "Cambodia", slug: "cambodia" },
  KI: { ru: "Кирибати", gen: "Кирибати", en: "Kiribati", slug: "kiribati" },
  KM: { ru: "Коморы", gen: "Комор", en: "Comoros", slug: "comoros" },
  KN: { ru: "Сент-Китс и Невис", gen: "Сент-Китса и Невиса", en: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis" },
  KR: { ru: "Южная Корея", gen: "Южной Кореи", en: "South Korea", slug: "south-korea" },
  KW: { ru: "Кувейт", gen: "Кувейта", en: "Kuwait", slug: "kuwait" },
  KY: { ru: "Каймановы острова", gen: "Каймановых островов", en: "Cayman Islands", slug: "cayman-islands" },
  KZ: { ru: "Казахстан", gen: "Казахстана", en: "Kazakhstan", slug: "kazakhstan" },
  LA: { ru: "Лаос", gen: "Лаоса", en: "Laos", slug: "laos" },
  LB: { ru: "Ливан", gen: "Ливана", en: "Lebanon", slug: "lebanon" },
  LC: { ru: "Сент-Люсия", gen: "Сент-Люсии", en: "Saint Lucia", slug: "saint-lucia" },
  LI: { ru: "Лихтенштейн", gen: "Лихтенштейна", en: "Liechtenstein", slug: "liechtenstein" },
  LK: { ru: "Шри-Ланка", gen: "Шри-Ланки", en: "Sri Lanka", slug: "sri-lanka" },
  LR: { ru: "Либерия", gen: "Либерии", en: "Liberia", slug: "liberia" },
  LS: { ru: "Лесото", gen: "Лесото", en: "Lesotho", slug: "lesotho" },
  LT: { ru: "Литва", gen: "Литвы", en: "Lithuania", slug: "lithuania" },
  LU: { ru: "Люксембург", gen: "Люксембурга", en: "Luxembourg", slug: "luxembourg" },
  LV: { ru: "Латвия", gen: "Латвии", en: "Latvia", slug: "latvia" },
  LY: { ru: "Ливия", gen: "Ливии", en: "Libya", slug: "libya" },
  MA: { ru: "Марокко", gen: "Марокко", en: "Morocco", slug: "morocco" },
  MC: { ru: "Монако", gen: "Монако", en: "Monaco", slug: "monaco" },
  MD: { ru: "Молдова", gen: "Молдовы", en: "Moldova", slug: "moldova" },
  ME: { ru: "Черногория", gen: "Черногории", en: "Montenegro", slug: "montenegro" },
  MF: { ru: "Сен-Мартен", gen: "Сен-Мартена", en: "Saint Martin", slug: "saint-martin" },
  MG: { ru: "Мадагаскар", gen: "Мадагаскара", en: "Madagascar", slug: "madagascar" },
  MH: { ru: "Маршалловы Острова", gen: "Маршалловых Островов", en: "Marshall Islands", slug: "marshall-islands" },
  MK: { ru: "Северная Македония", gen: "Северной Македонии", en: "North Macedonia", slug: "north-macedonia" },
  ML: { ru: "Мали", gen: "Мали", en: "Mali", slug: "mali" },
  MM: { ru: "Мьянма", gen: "Мьянмы", en: "Myanmar", slug: "myanmar" },
  MN: { ru: "Монголия", gen: "Монголии", en: "Mongolia", slug: "mongolia" },
  MO: { ru: "Макао", gen: "Макао", en: "Macao", slug: "macau" },
  MP: { ru: "Северные Марианские острова", gen: "Северных Марианских островов", en: "Northern Mariana Islands", slug: "northern-mariana-islands" },
  MQ: { ru: "Мартиника", gen: "Мартиники", en: "Martinique", slug: "martinique" },
  MR: { ru: "Мавритания", gen: "Мавритании", en: "Mauritania", slug: "mauritania" },
  MS: { ru: "Монтсеррат", gen: "Монтсеррата", en: "Montserrat", slug: "montserrat" },
  MT: { ru: "Мальта", gen: "Мальты", en: "Malta", slug: "malta" },
  MU: { ru: "Маврикий", gen: "Маврикия", en: "Mauritius", slug: "mauritius" },
  MV: { ru: "Мальдивы", gen: "Мальдив", en: "Maldives", slug: "maldives" },
  MW: { ru: "Малави", gen: "Малави", en: "Malawi", slug: "malawi" },
  MX: { ru: "Мексика", gen: "Мексики", en: "Mexico", slug: "mexico" },
  MY: { ru: "Малайзия", gen: "Малайзии", en: "Malaysia", slug: "malaysia" },
  MZ: { ru: "Мозамбик", gen: "Мозамбика", en: "Mozambique", slug: "mozambique" },
  NA: { ru: "Намибия", gen: "Намибии", en: "Namibia", slug: "namibia" },
  NC: { ru: "Новая Каледония", gen: "Новой Каледонии", en: "New Caledonia", slug: "new-caledonia" },
  NE: { ru: "Нигер", gen: "Нигера", en: "Niger", slug: "niger" },
  NG: { ru: "Нигерия", gen: "Нигерии", en: "Nigeria", slug: "nigeria" },
  NI: { ru: "Никарагуа", gen: "Никарагуа", en: "Nicaragua", slug: "nicaragua" },
  NL: { ru: "Нидерланды", gen: "Нидерландов", en: "Netherlands", slug: "netherlands" },
  NO: { ru: "Норвегия", gen: "Норвегии", en: "Norway", slug: "norway" },
  NP: { ru: "Непал", gen: "Непала", en: "Nepal", slug: "nepal" },
  NR: { ru: "Науру", gen: "Науру", en: "Nauru", slug: "nauru" },
  NU: { ru: "Ниуэ", gen: "Ниуэ", en: "Niue", slug: "niue" },
  NZ: { ru: "Новая Зеландия", gen: "Новой Зеландии", en: "New Zealand", slug: "new-zealand" },
  OM: { ru: "Оман", gen: "Омана", en: "Oman", slug: "oman" },
  PA: { ru: "Панама", gen: "Панамы", en: "Panama", slug: "panama" },
  PE: { ru: "Перу", gen: "Перу", en: "Peru", slug: "peru" },
  PF: { ru: "Французская Полинезия", gen: "Французской Полинезии", en: "French Polynesia", slug: "french-polynesia" },
  PG: { ru: "Папуа — Новая Гвинея", gen: "Папуа — Новой Гвинеи", en: "Papua New Guinea", slug: "papua-new-guinea" },
  PH: { ru: "Филиппины", gen: "Филиппин", en: "Philippines", slug: "philippines" },
  PK: { ru: "Пакистан", gen: "Пакистана", en: "Pakistan", slug: "pakistan" },
  PL: { ru: "Польша", gen: "Польши", en: "Poland", slug: "poland" },
  PM: { ru: "Сен-Пьер и Микелон", gen: "Сен-Пьера и Микелона", en: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon" },
  PR: { ru: "Пуэрто-Рико", gen: "Пуэрто-Рико", en: "Puerto Rico", slug: "puerto-rico" },
  PS: { ru: "Палестина", gen: "Палестины", en: "Palestinian Territories", slug: "palestine" },
  PT: { ru: "Португалия", gen: "Португалии", en: "Portugal", slug: "portugal" },
  PW: { ru: "Палау", gen: "Палау", en: "Palau", slug: "palau" },
  PY: { ru: "Парагвай", gen: "Парагвая", en: "Paraguay", slug: "paraguay" },
  QA: { ru: "Катар", gen: "Катара", en: "Qatar", slug: "qatar" },
  RE: { ru: "Реюньон", gen: "Реюньона", en: "Réunion", slug: "reunion" },
  RO: { ru: "Румыния", gen: "Румынии", en: "Romania", slug: "romania" },
  RS: { ru: "Сербия", gen: "Сербии", en: "Serbia", slug: "serbia" },
  RU: { ru: "Россия", gen: "России", en: "Russia", slug: "russia" },
  RW: { ru: "Руанда", gen: "Руанды", en: "Rwanda", slug: "rwanda" },
  SA: { ru: "Саудовская Аравия", gen: "Саудовской Аравии", en: "Saudi Arabia", slug: "saudi-arabia" },
  SB: { ru: "Соломоновы Острова", gen: "Соломоновых Островов", en: "Solomon Islands", slug: "solomon-islands" },
  SC: { ru: "Сейшелы", gen: "Сейшел", en: "Seychelles", slug: "seychelles" },
  SD: { ru: "Судан", gen: "Судана", en: "Sudan", slug: "sudan" },
  SE: { ru: "Швеция", gen: "Швеции", en: "Sweden", slug: "sweden" },
  SG: { ru: "Сингапур", gen: "Сингапура", en: "Singapore", slug: "singapore" },
  SI: { ru: "Словения", gen: "Словении", en: "Slovenia", slug: "slovenia" },
  SK: { ru: "Словакия", gen: "Словакии", en: "Slovakia", slug: "slovakia" },
  SL: { ru: "Сьерра-Леоне", gen: "Сьерра-Леоне", en: "Sierra Leone", slug: "sierra-leone" },
  SM: { ru: "Сан-Марино", gen: "Сан-Марино", en: "San Marino", slug: "san-marino" },
  SN: { ru: "Сенегал", gen: "Сенегала", en: "Senegal", slug: "senegal" },
  SO: { ru: "Сомали", gen: "Сомали", en: "Somalia", slug: "somalia" },
  SR: { ru: "Суринам", gen: "Суринама", en: "Suriname", slug: "suriname" },
  SS: { ru: "Южный Судан", gen: "Южного Судана", en: "South Sudan", slug: "south-sudan" },
  ST: { ru: "Сан-Томе и Принсипи", gen: "Сан-Томе и Принсипи", en: "São Tomé and Príncipe", slug: "sao-tome-and-principe" },
  SV: { ru: "Сальвадор", gen: "Сальвадора", en: "El Salvador", slug: "el-salvador" },
  SX: { ru: "Синт-Мартен", gen: "Синт-Мартена", en: "Sint Maarten", slug: "sint-maarten" },
  SY: { ru: "Сирия", gen: "Сирии", en: "Syria", slug: "syria" },
  SZ: { ru: "Эсватини", gen: "Эсватини", en: "Eswatini", slug: "eswatini" },
  TC: { ru: "Тёркс и Кайкос", gen: "Тёркса и Кайкоса", en: "Turks and Caicos Islands", slug: "turks-and-caicos" },
  TD: { ru: "Чад", gen: "Чада", en: "Chad", slug: "chad" },
  TG: { ru: "Того", gen: "Того", en: "Togo", slug: "togo" },
  TH: { ru: "Таиланд", gen: "Таиланда", en: "Thailand", slug: "thailand" },
  TJ: { ru: "Таджикистан", gen: "Таджикистана", en: "Tajikistan", slug: "tajikistan" },
  TL: { ru: "Восточный Тимор", gen: "Восточного Тимора", en: "Timor-Leste", slug: "timor-leste" },
  TM: { ru: "Туркменистан", gen: "Туркменистана", en: "Turkmenistan", slug: "turkmenistan" },
  TN: { ru: "Тунис", gen: "Туниса", en: "Tunisia", slug: "tunisia" },
  TO: { ru: "Тонга", gen: "Тонга", en: "Tonga", slug: "tonga" },
  TR: { ru: "Турция", gen: "Турции", en: "Türkiye", slug: "turkey" },
  TT: { ru: "Тринидад и Тобаго", gen: "Тринидада и Тобаго", en: "Trinidad and Tobago", slug: "trinidad-and-tobago" },
  TV: { ru: "Тувалу", gen: "Тувалу", en: "Tuvalu", slug: "tuvalu" },
  TW: { ru: "Тайвань", gen: "Тайваня", en: "Taiwan", slug: "taiwan" },
  TZ: { ru: "Танзания", gen: "Танзании", en: "Tanzania", slug: "tanzania" },
  UA: { ru: "Украина", gen: "Украины", en: "Ukraine", slug: "ukraine" },
  UG: { ru: "Уганда", gen: "Уганды", en: "Uganda", slug: "uganda" },
  US: { ru: "США", gen: "США", en: "United States", slug: "usa" },
  UY: { ru: "Уругвай", gen: "Уругвая", en: "Uruguay", slug: "uruguay" },
  VA: { ru: "Ватикан", gen: "Ватикана", en: "Vatican City", slug: "vatican" },
  UZ: { ru: "Узбекистан", gen: "Узбекистана", en: "Uzbekistan", slug: "uzbekistan" },
  VC: { ru: "Сент-Винсент и Гренадины", gen: "Сент-Винсента и Гренадин", en: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines" },
  VE: { ru: "Венесуэла", gen: "Венесуэлы", en: "Venezuela", slug: "venezuela" },
  VG: { ru: "Британские Виргинские острова", gen: "Британских Виргинских островов", en: "British Virgin Islands", slug: "british-virgin-islands" },
  VI: { ru: "Американские Виргинские острова", gen: "Американских Виргинских островов", en: "U.S. Virgin Islands", slug: "us-virgin-islands" },
  VN: { ru: "Вьетнам", gen: "Вьетнама", en: "Vietnam", slug: "vietnam" },
  VU: { ru: "Вануату", gen: "Вануату", en: "Vanuatu", slug: "vanuatu" },
  WS: { ru: "Самоа", gen: "Самоа", en: "Samoa", slug: "samoa" },
  XK: { ru: "Косово", gen: "Косово", en: "Kosovo", slug: "kosovo" },
  YE: { ru: "Йемен", gen: "Йемена", en: "Yemen", slug: "yemen" },
  YT: { ru: "Майотта", gen: "Майотты", en: "Mayotte", slug: "mayotte" },
  ZA: { ru: "ЮАР", gen: "ЮАР", en: "South Africa", slug: "south-africa" },
  ZM: { ru: "Замбия", gen: "Замбии", en: "Zambia", slug: "zambia" },
  ZW: { ru: "Зимбабве", gen: "Зимбабве", en: "Zimbabwe", slug: "zimbabwe" },
});

export const flagEmoji = (iso) => String(iso || '').toUpperCase().replace(/[A-Z]/g,
  (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));

