// ISO 3166-1 alpha-2 → Russian name and the Latin slug used in the URL.
//
// Data, not copy: a country's name and its conventional Latin spelling are
// facts, and the generator needs both so it never has to invent either the
// heading on a page or the address of one. A country absent from this table
// simply gets no page — silently guessing a transliteration would produce a
// URL nobody can link to and search engines would treat as a soft 404.
export const COUNTRY_NAMES = Object.freeze({
  AD: { ru: "Андорра", en: "Andorra", slug: "andorra" },
  AE: { ru: "ОАЭ", en: "United Arab Emirates", slug: "uae" },
  AF: { ru: "Афганистан", en: "Afghanistan", slug: "afghanistan" },
  AG: { ru: "Антигуа и Барбуда", en: "Antigua and Barbuda", slug: "antigua-and-barbuda" },
  AI: { ru: "Ангилья", en: "Anguilla", slug: "anguilla" },
  AN: { ru: 'Нидерландские Антильские острова', en: "Netherlands Antilles", slug: 'netherlands-antilles' },
  AL: { ru: "Албания", en: "Albania", slug: "albania" },
  AM: { ru: "Армения", en: "Armenia", slug: "armenia" },
  AO: { ru: "Ангола", en: "Angola", slug: "angola" },
  AR: { ru: "Аргентина", en: "Argentina", slug: "argentina" },
  AS: { ru: "Американское Самоа", en: "American Samoa", slug: "american-samoa" },
  AT: { ru: "Австрия", en: "Austria", slug: "austria" },
  AU: { ru: "Австралия", en: "Australia", slug: "australia" },
  AW: { ru: "Аруба", en: "Aruba", slug: "aruba" },
  AX: { ru: "Аландские острова", en: "Åland Islands", slug: "aland-islands" },
  AZ: { ru: "Азербайджан", en: "Azerbaijan", slug: "azerbaijan" },
  BA: { ru: "Босния и Герцеговина", en: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina" },
  BB: { ru: "Барбадос", en: "Barbados", slug: "barbados" },
  BD: { ru: "Бангладеш", en: "Bangladesh", slug: "bangladesh" },
  BE: { ru: "Бельгия", en: "Belgium", slug: "belgium" },
  BF: { ru: "Буркина-Фасо", en: "Burkina Faso", slug: "burkina-faso" },
  BG: { ru: "Болгария", en: "Bulgaria", slug: "bulgaria" },
  BH: { ru: "Бахрейн", en: "Bahrain", slug: "bahrain" },
  BI: { ru: "Бурунди", en: "Burundi", slug: "burundi" },
  BJ: { ru: "Бенин", en: "Benin", slug: "benin" },
  BL: { ru: "Сен-Бартелеми", en: "Saint Barthélemy", slug: "saint-barthelemy" },
  BM: { ru: "Бермуды", en: "Bermuda", slug: "bermuda" },
  BN: { ru: "Бруней", en: "Brunei", slug: "brunei" },
  BO: { ru: "Боливия", en: "Bolivia", slug: "bolivia" },
  BQ: { ru: "Бонайре", en: "Caribbean Netherlands", slug: "bonaire" },
  BR: { ru: "Бразилия", en: "Brazil", slug: "brazil" },
  BS: { ru: "Багамы", en: "Bahamas", slug: "bahamas" },
  BT: { ru: "Бутан", en: "Bhutan", slug: "bhutan" },
  BW: { ru: "Ботсвана", en: "Botswana", slug: "botswana" },
  BY: { ru: "Беларусь", en: "Belarus", slug: "belarus" },
  BZ: { ru: "Белиз", en: "Belize", slug: "belize" },
  CA: { ru: "Канада", en: "Canada", slug: "canada" },
  CD: { ru: "ДР Конго", en: "DR Congo", slug: "dr-congo" },
  CF: { ru: "ЦАР", en: "Central African Republic", slug: "central-african-republic" },
  CG: { ru: "Конго", en: "Republic of the Congo", slug: "congo" },
  CH: { ru: "Швейцария", en: "Switzerland", slug: "switzerland" },
  CI: { ru: "Кот-д’Ивуар", en: "Côte d’Ivoire", slug: "ivory-coast" },
  CK: { ru: "Острова Кука", en: "Cook Islands", slug: "cook-islands" },
  CL: { ru: "Чили", en: "Chile", slug: "chile" },
  CM: { ru: "Камерун", en: "Cameroon", slug: "cameroon" },
  CN: { ru: "Китай", en: "China", slug: "china" },
  CO: { ru: "Колумбия", en: "Colombia", slug: "colombia" },
  CR: { ru: "Коста-Рика", en: "Costa Rica", slug: "costa-rica" },
  CU: { ru: "Куба", en: "Cuba", slug: "cuba" },
  CV: { ru: "Кабо-Верде", en: "Cape Verde", slug: "cape-verde" },
  CW: { ru: "Кюрасао", en: "Curaçao", slug: "curacao" },
  CY: { ru: "Кипр", en: "Cyprus", slug: "cyprus" },
  CZ: { ru: "Чехия", en: "Czechia", slug: "czechia" },
  DE: { ru: "Германия", en: "Germany", slug: "germany" },
  DJ: { ru: "Джибути", en: "Djibouti", slug: "djibouti" },
  DK: { ru: "Дания", en: "Denmark", slug: "denmark" },
  DM: { ru: "Доминика", en: "Dominica", slug: "dominica" },
  DO: { ru: "Доминикана", en: "Dominican Republic", slug: "dominican-republic" },
  DZ: { ru: "Алжир", en: "Algeria", slug: "algeria" },
  EC: { ru: "Эквадор", en: "Ecuador", slug: "ecuador" },
  EE: { ru: "Эстония", en: "Estonia", slug: "estonia" },
  EG: { ru: "Египет", en: "Egypt", slug: "egypt" },
  ER: { ru: "Эритрея", en: "Eritrea", slug: "eritrea" },
  ES: { ru: "Испания", en: "Spain", slug: "spain" },
  ET: { ru: "Эфиопия", en: "Ethiopia", slug: "ethiopia" },
  FI: { ru: "Финляндия", en: "Finland", slug: "finland" },
  FJ: { ru: "Фиджи", en: "Fiji", slug: "fiji" },
  FK: { ru: "Фолклендские острова", en: "Falkland Islands", slug: "falkland-islands" },
  FM: { ru: "Микронезия", en: "Micronesia", slug: "micronesia" },
  FO: { ru: "Фарерские острова", en: "Faroe Islands", slug: "faroe-islands" },
  FR: { ru: "Франция", en: "France", slug: "france" },
  GA: { ru: "Габон", en: "Gabon", slug: "gabon" },
  GB: { ru: "Великобритания", en: "United Kingdom", slug: "united-kingdom" },
  GD: { ru: "Гренада", en: "Grenada", slug: "grenada" },
  GE: { ru: "Грузия", en: "Georgia", slug: "georgia" },
  GF: { ru: "Французская Гвиана", en: "French Guiana", slug: "french-guiana" },
  GG: { ru: "Гернси", en: "Guernsey", slug: "guernsey" },
  GH: { ru: "Гана", en: "Ghana", slug: "ghana" },
  GI: { ru: "Гибралтар", en: "Gibraltar", slug: "gibraltar" },
  GL: { ru: "Гренландия", en: "Greenland", slug: "greenland" },
  GM: { ru: "Гамбия", en: "Gambia", slug: "gambia" },
  GN: { ru: "Гвинея", en: "Guinea", slug: "guinea" },
  GP: { ru: "Гваделупа", en: "Guadeloupe", slug: "guadeloupe" },
  GQ: { ru: "Экваториальная Гвинея", en: "Equatorial Guinea", slug: "equatorial-guinea" },
  GR: { ru: "Греция", en: "Greece", slug: "greece" },
  GT: { ru: "Гватемала", en: "Guatemala", slug: "guatemala" },
  GU: { ru: "Гуам", en: "Guam", slug: "guam" },
  GW: { ru: "Гвинея-Бисау", en: "Guinea-Bissau", slug: "guinea-bissau" },
  GY: { ru: "Гайана", en: "Guyana", slug: "guyana" },
  HK: { ru: "Гонконг", en: "Hong Kong", slug: "hong-kong" },
  HN: { ru: "Гондурас", en: "Honduras", slug: "honduras" },
  HR: { ru: "Хорватия", en: "Croatia", slug: "croatia" },
  HT: { ru: "Гаити", en: "Haiti", slug: "haiti" },
  HU: { ru: "Венгрия", en: "Hungary", slug: "hungary" },
  ID: { ru: "Индонезия", en: "Indonesia", slug: "indonesia" },
  IE: { ru: "Ирландия", en: "Ireland", slug: "ireland" },
  IL: { ru: "Израиль", en: "Israel", slug: "israel" },
  IM: { ru: "Остров Мэн", en: "Isle of Man", slug: "isle-of-man" },
  IN: { ru: "Индия", en: "India", slug: "india" },
  IQ: { ru: "Ирак", en: "Iraq", slug: "iraq" },
  IR: { ru: "Иран", en: "Iran", slug: "iran" },
  IS: { ru: "Исландия", en: "Iceland", slug: "iceland" },
  IT: { ru: "Италия", en: "Italy", slug: "italy" },
  JE: { ru: "Джерси", en: "Jersey", slug: "jersey" },
  JM: { ru: "Ямайка", en: "Jamaica", slug: "jamaica" },
  JO: { ru: "Иордания", en: "Jordan", slug: "jordan" },
  JP: { ru: "Япония", en: "Japan", slug: "japan" },
  KE: { ru: "Кения", en: "Kenya", slug: "kenya" },
  KG: { ru: "Киргизия", en: "Kyrgyzstan", slug: "kyrgyzstan" },
  KH: { ru: "Камбоджа", en: "Cambodia", slug: "cambodia" },
  KI: { ru: "Кирибати", en: "Kiribati", slug: "kiribati" },
  KM: { ru: "Коморы", en: "Comoros", slug: "comoros" },
  KN: { ru: "Сент-Китс и Невис", en: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis" },
  KR: { ru: "Южная Корея", en: "South Korea", slug: "south-korea" },
  KW: { ru: "Кувейт", en: "Kuwait", slug: "kuwait" },
  KY: { ru: "Каймановы острова", en: "Cayman Islands", slug: "cayman-islands" },
  KZ: { ru: "Казахстан", en: "Kazakhstan", slug: "kazakhstan" },
  LA: { ru: "Лаос", en: "Laos", slug: "laos" },
  LB: { ru: "Ливан", en: "Lebanon", slug: "lebanon" },
  LC: { ru: "Сент-Люсия", en: "Saint Lucia", slug: "saint-lucia" },
  LI: { ru: "Лихтенштейн", en: "Liechtenstein", slug: "liechtenstein" },
  LK: { ru: "Шри-Ланка", en: "Sri Lanka", slug: "sri-lanka" },
  LR: { ru: "Либерия", en: "Liberia", slug: "liberia" },
  LS: { ru: "Лесото", en: "Lesotho", slug: "lesotho" },
  LT: { ru: "Литва", en: "Lithuania", slug: "lithuania" },
  LU: { ru: "Люксембург", en: "Luxembourg", slug: "luxembourg" },
  LV: { ru: "Латвия", en: "Latvia", slug: "latvia" },
  LY: { ru: "Ливия", en: "Libya", slug: "libya" },
  MA: { ru: "Марокко", en: "Morocco", slug: "morocco" },
  MC: { ru: "Монако", en: "Monaco", slug: "monaco" },
  MD: { ru: "Молдова", en: "Moldova", slug: "moldova" },
  ME: { ru: "Черногория", en: "Montenegro", slug: "montenegro" },
  MF: { ru: "Сен-Мартен", en: "Saint Martin", slug: "saint-martin" },
  MG: { ru: "Мадагаскар", en: "Madagascar", slug: "madagascar" },
  MH: { ru: "Маршалловы Острова", en: "Marshall Islands", slug: "marshall-islands" },
  MK: { ru: "Северная Македония", en: "North Macedonia", slug: "north-macedonia" },
  ML: { ru: "Мали", en: "Mali", slug: "mali" },
  MM: { ru: "Мьянма", en: "Myanmar", slug: "myanmar" },
  MN: { ru: "Монголия", en: "Mongolia", slug: "mongolia" },
  MO: { ru: "Макао", en: "Macao", slug: "macau" },
  MP: { ru: "Северные Марианские острова", en: "Northern Mariana Islands", slug: "northern-mariana-islands" },
  MQ: { ru: "Мартиника", en: "Martinique", slug: "martinique" },
  MR: { ru: "Мавритания", en: "Mauritania", slug: "mauritania" },
  MS: { ru: "Монтсеррат", en: "Montserrat", slug: "montserrat" },
  MT: { ru: "Мальта", en: "Malta", slug: "malta" },
  MU: { ru: "Маврикий", en: "Mauritius", slug: "mauritius" },
  MV: { ru: "Мальдивы", en: "Maldives", slug: "maldives" },
  MW: { ru: "Малави", en: "Malawi", slug: "malawi" },
  MX: { ru: "Мексика", en: "Mexico", slug: "mexico" },
  MY: { ru: "Малайзия", en: "Malaysia", slug: "malaysia" },
  MZ: { ru: "Мозамбик", en: "Mozambique", slug: "mozambique" },
  NA: { ru: "Намибия", en: "Namibia", slug: "namibia" },
  NC: { ru: "Новая Каледония", en: "New Caledonia", slug: "new-caledonia" },
  NE: { ru: "Нигер", en: "Niger", slug: "niger" },
  NG: { ru: "Нигерия", en: "Nigeria", slug: "nigeria" },
  NI: { ru: "Никарагуа", en: "Nicaragua", slug: "nicaragua" },
  NL: { ru: "Нидерланды", en: "Netherlands", slug: "netherlands" },
  NO: { ru: "Норвегия", en: "Norway", slug: "norway" },
  NP: { ru: "Непал", en: "Nepal", slug: "nepal" },
  NR: { ru: "Науру", en: "Nauru", slug: "nauru" },
  NU: { ru: "Ниуэ", en: "Niue", slug: "niue" },
  NZ: { ru: "Новая Зеландия", en: "New Zealand", slug: "new-zealand" },
  OM: { ru: "Оман", en: "Oman", slug: "oman" },
  PA: { ru: "Панама", en: "Panama", slug: "panama" },
  PE: { ru: "Перу", en: "Peru", slug: "peru" },
  PF: { ru: "Французская Полинезия", en: "French Polynesia", slug: "french-polynesia" },
  PG: { ru: "Папуа — Новая Гвинея", en: "Papua New Guinea", slug: "papua-new-guinea" },
  PH: { ru: "Филиппины", en: "Philippines", slug: "philippines" },
  PK: { ru: "Пакистан", en: "Pakistan", slug: "pakistan" },
  PL: { ru: "Польша", en: "Poland", slug: "poland" },
  PM: { ru: "Сен-Пьер и Микелон", en: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon" },
  PR: { ru: "Пуэрто-Рико", en: "Puerto Rico", slug: "puerto-rico" },
  PS: { ru: "Палестина", en: "Palestinian Territories", slug: "palestine" },
  PT: { ru: "Португалия", en: "Portugal", slug: "portugal" },
  PW: { ru: "Палау", en: "Palau", slug: "palau" },
  PY: { ru: "Парагвай", en: "Paraguay", slug: "paraguay" },
  QA: { ru: "Катар", en: "Qatar", slug: "qatar" },
  RE: { ru: "Реюньон", en: "Réunion", slug: "reunion" },
  RO: { ru: "Румыния", en: "Romania", slug: "romania" },
  RS: { ru: "Сербия", en: "Serbia", slug: "serbia" },
  RU: { ru: "Россия", en: "Russia", slug: "russia" },
  RW: { ru: "Руанда", en: "Rwanda", slug: "rwanda" },
  SA: { ru: "Саудовская Аравия", en: "Saudi Arabia", slug: "saudi-arabia" },
  SB: { ru: "Соломоновы Острова", en: "Solomon Islands", slug: "solomon-islands" },
  SC: { ru: "Сейшелы", en: "Seychelles", slug: "seychelles" },
  SD: { ru: "Судан", en: "Sudan", slug: "sudan" },
  SE: { ru: "Швеция", en: "Sweden", slug: "sweden" },
  SG: { ru: "Сингапур", en: "Singapore", slug: "singapore" },
  SI: { ru: "Словения", en: "Slovenia", slug: "slovenia" },
  SK: { ru: "Словакия", en: "Slovakia", slug: "slovakia" },
  SL: { ru: "Сьерра-Леоне", en: "Sierra Leone", slug: "sierra-leone" },
  SM: { ru: "Сан-Марино", en: "San Marino", slug: "san-marino" },
  SN: { ru: "Сенегал", en: "Senegal", slug: "senegal" },
  SO: { ru: "Сомали", en: "Somalia", slug: "somalia" },
  SR: { ru: "Суринам", en: "Suriname", slug: "suriname" },
  SS: { ru: "Южный Судан", en: "South Sudan", slug: "south-sudan" },
  ST: { ru: "Сан-Томе и Принсипи", en: "São Tomé and Príncipe", slug: "sao-tome-and-principe" },
  SV: { ru: "Сальвадор", en: "El Salvador", slug: "el-salvador" },
  SX: { ru: "Синт-Мартен", en: "Sint Maarten", slug: "sint-maarten" },
  SY: { ru: "Сирия", en: "Syria", slug: "syria" },
  SZ: { ru: "Эсватини", en: "Eswatini", slug: "eswatini" },
  TC: { ru: "Тёркс и Кайкос", en: "Turks and Caicos Islands", slug: "turks-and-caicos" },
  TD: { ru: "Чад", en: "Chad", slug: "chad" },
  TG: { ru: "Того", en: "Togo", slug: "togo" },
  TH: { ru: "Таиланд", en: "Thailand", slug: "thailand" },
  TJ: { ru: "Таджикистан", en: "Tajikistan", slug: "tajikistan" },
  TL: { ru: "Восточный Тимор", en: "Timor-Leste", slug: "timor-leste" },
  TM: { ru: "Туркменистан", en: "Turkmenistan", slug: "turkmenistan" },
  TN: { ru: "Тунис", en: "Tunisia", slug: "tunisia" },
  TO: { ru: "Тонга", en: "Tonga", slug: "tonga" },
  TR: { ru: "Турция", en: "Türkiye", slug: "turkey" },
  TT: { ru: "Тринидад и Тобаго", en: "Trinidad and Tobago", slug: "trinidad-and-tobago" },
  TV: { ru: "Тувалу", en: "Tuvalu", slug: "tuvalu" },
  TW: { ru: "Тайвань", en: "Taiwan", slug: "taiwan" },
  TZ: { ru: "Танзания", en: "Tanzania", slug: "tanzania" },
  UA: { ru: "Украина", en: "Ukraine", slug: "ukraine" },
  UG: { ru: "Уганда", en: "Uganda", slug: "uganda" },
  US: { ru: "США", en: "United States", slug: "usa" },
  UY: { ru: "Уругвай", en: "Uruguay", slug: "uruguay" },
  VA: { ru: "Ватикан", en: "Vatican City", slug: "vatican" },
  UZ: { ru: "Узбекистан", en: "Uzbekistan", slug: "uzbekistan" },
  VC: { ru: "Сент-Винсент и Гренадины", en: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines" },
  VE: { ru: "Венесуэла", en: "Venezuela", slug: "venezuela" },
  VG: { ru: "Британские Виргинские острова", en: "British Virgin Islands", slug: "british-virgin-islands" },
  VI: { ru: "Американские Виргинские острова", en: "U.S. Virgin Islands", slug: "us-virgin-islands" },
  VN: { ru: "Вьетнам", en: "Vietnam", slug: "vietnam" },
  VU: { ru: "Вануату", en: "Vanuatu", slug: "vanuatu" },
  WS: { ru: "Самоа", en: "Samoa", slug: "samoa" },
  XK: { ru: "Косово", en: "Kosovo", slug: "kosovo" },
  YE: { ru: "Йемен", en: "Yemen", slug: "yemen" },
  YT: { ru: "Майотта", en: "Mayotte", slug: "mayotte" },
  ZA: { ru: "ЮАР", en: "South Africa", slug: "south-africa" },
  ZM: { ru: "Замбия", en: "Zambia", slug: "zambia" },
  ZW: { ru: "Зимбабве", en: "Zimbabwe", slug: "zimbabwe" },
});

export const flagEmoji = (iso) => String(iso || '').toUpperCase().replace(/[A-Z]/g,
  (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));

