'use strict';

/* ============================================================================
 * Magic eSIM Mini App — the part with no DOM in it.
 *
 * Everything here is testable in Node, and that is the reason it exists as its
 * own file: the interesting behaviour of this app is not layout, it is what
 * happens when the network is unreliable and when a customer taps twice.
 *
 * THREE RULES THIS FILE ENFORCES
 *
 *   1. Reads may be retried. Writes may not — not blindly. A GET that fails
 *      costs a second request; a POST that fails might have succeeded on the
 *      server, and repeating it without an idempotency key is how one tap
 *      becomes two orders. So retry is opt-in per call and the purchase path
 *      carries a key that survives the retry.
 *
 *   2. A single 502 must not look like a broken app. TD-55 (R-38) means the
 *      gateway drops a real share of requests — measured at 20-35% on a bad
 *      minute, with origin healthy throughout. So reads retry with backoff, and
 *      when they still fail the app shows the last good answer with an honest
 *      "shown from cache" rather than an empty screen or an endless spinner.
 *
 *   3. Never invent a number. A usage figure the app could not fetch is
 *      rendered as unknown, never as zero. "0 GB left" and "we could not ask"
 *      look identical in a progress bar and mean opposite things to somebody
 *      standing in an airport.
 * ========================================================================= */

/* --------------------------------------------------------------------------
 * Country names
 *
 * The catalogue DTO carries no name a customer can read: `coverage_countries`
 * is empty on all 973 packages, `name` is English ("Netherlands 3GB 15Days"),
 * and there is no `country` field at all — so the Mini App shipped a country
 * list reading "AD · AE · AF · AF-29 · AG". Blueprint P3 forbids exactly that:
 * the customer never sees an internal technical entity.
 *
 * The names are NOT redefined here. This block is generated from
 * seo/country-names.mjs by seo/build-country-dictionary.mjs — the same source
 * and the same script the storefront uses — and `--check` fails CI if it
 * drifts. Adding this file as a third target is why a new destination can no
 * longer reach the Mini App as a bare ISO code either.
 * ----------------------------------------------------------------------- */

/* --- COUNTRY NAMES ------------------------------------------------------
 * GENERATED by seo/build-country-dictionary.mjs from seo/country-names.mjs.
 * Do not edit by hand: both copies are rewritten from that source, and CI
 * fails when a code in the live catalogue has no name here, so a new
 * destination can no longer reach the storefront as a bare ISO code.
 * --------------------------------------------------------------------- */
const countryNames={
  AD:'Андорра',AE:'ОАЭ',AF:'Афганистан',AG:'Антигуа и Барбуда',AI:'Ангилья',AL:'Албания',
  AM:'Армения',AO:'Ангола',AR:'Аргентина',AS:'Американское Самоа',AT:'Австрия',AU:'Австралия',
  AW:'Аруба',AX:'Аландские острова',AZ:'Азербайджан',BA:'Босния и Герцеговина',BB:'Барбадос',
  BD:'Бангладеш',BE:'Бельгия',BF:'Буркина-Фасо',BG:'Болгария',BH:'Бахрейн',BI:'Бурунди',BJ:'Бенин',
  BL:'Сен-Бартелеми',BM:'Бермуды',BN:'Бруней',BO:'Боливия',BQ:'Бонэйр, Синт-Эстатиус и Саба',
  BR:'Бразилия',BS:'Багамы',BT:'Бутан',BW:'Ботсвана',BY:'Беларусь',BZ:'Белиз',CA:'Канада',
  CD:'ДР Конго',CF:'Центральноафриканская Республика',CG:'Республика Конго',CH:'Швейцария',
  CI:'Кот-д’Ивуар',CK:'Острова Кука',CL:'Чили',CM:'Камерун',CN:'Китай',CO:'Колумбия',
  CR:'Коста-Рика',CU:'Куба',CV:'Кабо-Верде',CW:'Кюрасао',CY:'Кипр',CZ:'Чехия',DE:'Германия',
  DJ:'Джибути',DK:'Дания',DM:'Доминика',DO:'Доминикана',DZ:'Алжир',EC:'Эквадор',EE:'Эстония',
  EG:'Египет',ER:'Эритрея',ES:'Испания',ET:'Эфиопия',FI:'Финляндия',FJ:'Фиджи',
  FK:'Фолклендские острова',FM:'Микронезия',FO:'Фарерские острова',FR:'Франция',GA:'Габон',
  GB:'Великобритания',GD:'Гренада',GE:'Грузия',GF:'Французская Гвиана',GG:'Гернси',GH:'Гана',
  GI:'Гибралтар',GL:'Гренландия',GM:'Гамбия',GN:'Гвинея',GP:'Гваделупа',GQ:'Экваториальная Гвинея',
  GR:'Греция',GT:'Гватемала',GU:'Гуам',GW:'Гвинея-Бисау',GY:'Гайана',HK:'Гонконг',HN:'Гондурас',
  HR:'Хорватия',HT:'Гаити',HU:'Венгрия',ID:'Индонезия',IE:'Ирландия',IL:'Израиль',IM:'Остров Мэн',
  IN:'Индия',IQ:'Ирак',IR:'Иран',IS:'Исландия',IT:'Италия',JE:'Джерси',JM:'Ямайка',JO:'Иордания',
  JP:'Япония',KE:'Кения',KG:'Киргизия',KH:'Камбоджа',KI:'Кирибати',KM:'Коморы',
  KN:'Сент-Китс и Невис',KR:'Южная Корея',KW:'Кувейт',KY:'Каймановы острова',KZ:'Казахстан',
  LA:'Лаос',LB:'Ливан',LC:'Сент-Люсия',LI:'Лихтенштейн',LK:'Шри-Ланка',LR:'Либерия',LS:'Лесото',
  LT:'Литва',LU:'Люксембург',LV:'Латвия',LY:'Ливия',MA:'Марокко',MC:'Монако',MD:'Молдова',
  ME:'Черногория',MF:'Сен-Мартен',MG:'Мадагаскар',MH:'Маршалловы Острова',MK:'Северная Македония',
  ML:'Мали',MM:'Мьянма',MN:'Монголия',MO:'Макао',MP:'Северные Марианские острова',MQ:'Мартиника',
  MR:'Мавритания',MS:'Монтсеррат',MT:'Мальта',MU:'Маврикий',MV:'Мальдивы',MW:'Малави',MX:'Мексика',
  MY:'Малайзия',MZ:'Мозамбик',NA:'Намибия',NC:'Новая Каледония',NE:'Нигер',NG:'Нигерия',
  NI:'Никарагуа',NL:'Нидерланды',NO:'Норвегия',NP:'Непал',NR:'Науру',NU:'Ниуэ',NZ:'Новая Зеландия',
  OM:'Оман',OTHER:'Другие страны',PA:'Панама',PE:'Перу',PF:'Французская Полинезия',
  PG:'Папуа — Новая Гвинея',PH:'Филиппины',PK:'Пакистан',PL:'Польша',PM:'Сен-Пьер и Микелон',
  PR:'Пуэрто-Рико',PS:'Палестина',PT:'Португалия',PW:'Палау',PY:'Парагвай',QA:'Катар',RE:'Реюньон',
  RO:'Румыния',RS:'Сербия',RU:'Россия',RW:'Руанда',SA:'Саудовская Аравия',SB:'Соломоновы Острова',
  SC:'Сейшелы',SD:'Судан',SE:'Швеция',SG:'Сингапур',SI:'Словения',SK:'Словакия',SL:'Сьерра-Леоне',
  SM:'Сан-Марино',SN:'Сенегал',SO:'Сомали',SR:'Суринам',SS:'Южный Судан',ST:'Сан-Томе и Принсипи',
  SV:'Сальвадор',SX:'Синт-Мартен',SY:'Сирия',SZ:'Эсватини',TC:'Теркс и Кайкос',TD:'Чад',TG:'Того',
  TH:'Таиланд',TJ:'Таджикистан',TL:'Восточный Тимор',TM:'Туркменистан',TN:'Тунис',TO:'Тонга',
  TR:'Турция',TT:'Тринидад и Тобаго',TV:'Тувалу',TW:'Тайвань',TZ:'Танзания',UA:'Украина',
  UG:'Уганда',US:'США',UY:'Уругвай',UZ:'Узбекистан',VA:'Ватикан',VC:'Сент-Винсент и Гренадины',
  VE:'Венесуэла',VG:'Британские Виргинские острова',VI:'Виргинские острова США',VN:'Вьетнам',
  VU:'Вануату',WS:'Самоа',XK:'Косово',YE:'Йемен',YT:'Майотта',ZA:'ЮАР',ZM:'Замбия',ZW:'Зимбабве',
};
/* --- END COUNTRY NAMES --- */

/* --- COUNTRY LATIN ------------------------------------------------------
 * GENERATED by seo/build-country-dictionary.mjs from seo/country-names.mjs.
 * The Latin slug per country, so search finds "thailand" and "uae" as well
 * as "Таиланд" and "ОАЭ". Same source as the URLs, so the two cannot part.
 * --------------------------------------------------------------------- */
const countryLatin={
  AD:'andorra',AE:'uae',AF:'afghanistan',AG:'antigua-and-barbuda',AI:'anguilla',AL:'albania',
  AM:'armenia',AO:'angola',AR:'argentina',AS:'american-samoa',AT:'austria',AU:'australia',
  AW:'aruba',AX:'aland-islands',AZ:'azerbaijan',BA:'bosnia-and-herzegovina',BB:'barbados',
  BD:'bangladesh',BE:'belgium',BF:'burkina-faso',BG:'bulgaria',BH:'bahrain',BI:'burundi',
  BJ:'benin',BL:'saint-barthelemy',BM:'bermuda',BN:'brunei',BO:'bolivia',BQ:'bonaire',BR:'brazil',
  BS:'bahamas',BT:'bhutan',BW:'botswana',BY:'belarus',BZ:'belize',CA:'canada',CD:'dr-congo',
  CF:'central-african-republic',CG:'congo',CH:'switzerland',CI:'ivory-coast',CK:'cook-islands',
  CL:'chile',CM:'cameroon',CN:'china',CO:'colombia',CR:'costa-rica',CU:'cuba',CV:'cape-verde',
  CW:'curacao',CY:'cyprus',CZ:'czechia',DE:'germany',DJ:'djibouti',DK:'denmark',DM:'dominica',
  DO:'dominican-republic',DZ:'algeria',EC:'ecuador',EE:'estonia',EG:'egypt',ER:'eritrea',
  ES:'spain',ET:'ethiopia',FI:'finland',FJ:'fiji',FK:'falkland-islands',FM:'micronesia',
  FO:'faroe-islands',FR:'france',GA:'gabon',GB:'united-kingdom',GD:'grenada',GE:'georgia',
  GF:'french-guiana',GG:'guernsey',GH:'ghana',GI:'gibraltar',GL:'greenland',GM:'gambia',
  GN:'guinea',GP:'guadeloupe',GQ:'equatorial-guinea',GR:'greece',GT:'guatemala',GU:'guam',
  GW:'guinea-bissau',GY:'guyana',HK:'hong-kong',HN:'honduras',HR:'croatia',HT:'haiti',HU:'hungary',
  ID:'indonesia',IE:'ireland',IL:'israel',IM:'isle-of-man',IN:'india',IQ:'iraq',IR:'iran',
  IS:'iceland',IT:'italy',JE:'jersey',JM:'jamaica',JO:'jordan',JP:'japan',KE:'kenya',
  KG:'kyrgyzstan',KH:'cambodia',KI:'kiribati',KM:'comoros',KN:'saint-kitts-and-nevis',
  KR:'south-korea',KW:'kuwait',KY:'cayman-islands',KZ:'kazakhstan',LA:'laos',LB:'lebanon',
  LC:'saint-lucia',LI:'liechtenstein',LK:'sri-lanka',LR:'liberia',LS:'lesotho',LT:'lithuania',
  LU:'luxembourg',LV:'latvia',LY:'libya',MA:'morocco',MC:'monaco',MD:'moldova',ME:'montenegro',
  MF:'saint-martin',MG:'madagascar',MH:'marshall-islands',MK:'north-macedonia',ML:'mali',
  MM:'myanmar',MN:'mongolia',MO:'macau',MP:'northern-mariana-islands',MQ:'martinique',
  MR:'mauritania',MS:'montserrat',MT:'malta',MU:'mauritius',MV:'maldives',MW:'malawi',MX:'mexico',
  MY:'malaysia',MZ:'mozambique',NA:'namibia',NC:'new-caledonia',NE:'niger',NG:'nigeria',
  NI:'nicaragua',NL:'netherlands',NO:'norway',NP:'nepal',NR:'nauru',NU:'niue',NZ:'new-zealand',
  OM:'oman',PA:'panama',PE:'peru',PF:'french-polynesia',PG:'papua-new-guinea',PH:'philippines',
  PK:'pakistan',PL:'poland',PM:'saint-pierre-and-miquelon',PR:'puerto-rico',PS:'palestine',
  PT:'portugal',PW:'palau',PY:'paraguay',QA:'qatar',RE:'reunion',RO:'romania',RS:'serbia',
  RU:'russia',RW:'rwanda',SA:'saudi-arabia',SB:'solomon-islands',SC:'seychelles',SD:'sudan',
  SE:'sweden',SG:'singapore',SI:'slovenia',SK:'slovakia',SL:'sierra-leone',SM:'san-marino',
  SN:'senegal',SO:'somalia',SR:'suriname',SS:'south-sudan',ST:'sao-tome-and-principe',
  SV:'el-salvador',SX:'sint-maarten',SY:'syria',SZ:'eswatini',TC:'turks-and-caicos',TD:'chad',
  TG:'togo',TH:'thailand',TJ:'tajikistan',TL:'timor-leste',TM:'turkmenistan',TN:'tunisia',
  TO:'tonga',TR:'turkey',TT:'trinidad-and-tobago',TV:'tuvalu',TW:'taiwan',TZ:'tanzania',
  UA:'ukraine',UG:'uganda',US:'usa',UY:'uruguay',UZ:'uzbekistan',VA:'vatican',
  VC:'saint-vincent-and-the-grenadines',VE:'venezuela',VG:'british-virgin-islands',
  VI:'us-virgin-islands',VN:'vietnam',VU:'vanuatu',WS:'samoa',XK:'kosovo',YE:'yemen',YT:'mayotte',
  ZA:'south-africa',ZM:'zambia',ZW:'zimbabwe',
};
/* --- END COUNTRY LATIN --- */

/* --- POPULAR COUNTRIES --------------------------------------------------
 * GENERATED by seo/build-country-dictionary.mjs by PARSING index.html.
 * These are the storefront's own tiles, in the storefront's own order —
 * not a second opinion about what is popular. Reorder the tiles on the
 * site and re-run the script; never edit this list by hand.
 * --------------------------------------------------------------------- */
const popularCountries=['TR','TH','VN','EG','MV','LK','CN','IT','AE','ID','JP','KR','ES','FR','GR','CY'];
/* --- END POPULAR COUNTRIES --- */

/* --- TARIFF WORDING -----------------------------------------------------
 * GENERATED by seo/build-country-dictionary.mjs from
 * assets/country-tariffs.js, where this wording has always been kept.
 *
 * Blueprint P8: the Mini App reuses the site's content instead of writing
 * its own. The risk of a hand copy here is not a missing string — it is the
 * same tariff described two different ways on two screens of one shop.
 * --------------------------------------------------------------------- */
const TARIFF_ACTIVATION_LABELS = {
  first_data_usage:'с первого использования интернета',
  first_network_connection:'с первого подключения к сети',
  network_connection:'с первого подключения к сети',
  upon_installation:'после установки eSIM',
  installation:'после установки eSIM',
  upon_purchase:'после покупки',
  purchase:'после покупки'
};
const TARIFF_ACTIVATION_FALLBACK = 'с первого подключения к сети';
const TARIFF_TEXT_RU = {
  // MobiMatter SPEED
  'unrestricted':'Без ограничений скорости.',
  'limited':'Действуют ограничения скорости.',
  '3gb/day at 20mbps. 1mbps afterwards.':'3 ГБ в день на скорости до 20 Мбит/с, далее до 1 Мбит/с.',
  '3gb/day high speed. 1mbps afterwards.':'3 ГБ в день на высокой скорости, далее до 1 Мбит/с.',
  'total 30 gb at full speed, 2mbps speed cap afterwards':'30 ГБ на полной скорости, далее до 2 Мбит/с.',
  'total 60 gb at full speed, 2mbps speed cap afterwards':'60 ГБ на полной скорости, далее до 2 Мбит/с.',
  'total 90 gb at full speed, 2mbps speed cap afterwards':'90 ГБ на полной скорости, далее до 2 Мбит/с.',
  // MobiMatter SPEED_LONG
  'full data speeds - no daily limits, no throttling':'Полная скорость без ежедневных лимитов и снижения скорости.',
  '3gb/day at 20mbps high speed. up to 1 mbps speed limit afterwards, resets every 24 hours. fair usage policy applies.':'3 ГБ в день на скорости до 20 Мбит/с, далее до 1 Мбит/с. Лимит обновляется каждые 24 часа, действует политика справедливого использования.',
  '3gb/day without a speed limit. up to 1 mbps speed limit afterwards, resets every 24 hours. fair usage policy applies.':'3 ГБ в день без ограничения скорости, далее до 1 Мбит/с. Лимит обновляется каждые 24 часа, действует политика справедливого использования.',
  'in case of exceeding daily 1 gb high-speed allowance, speed will be limited to 512 kbps for the remainder of the day, which may impact your experience with video streaming and other data-intensive applications.':'При расходе более 1 ГБ в день скорость снижается до 512 Кбит/с до конца суток. Это может повлиять на видео и другие ресурсоёмкие сервисы.',
  'no daily limits. speed restricted to 2 mbps if total consumption exceeds 30 gb':'Без ежедневных лимитов. При расходе свыше 30 ГБ скорость снижается до 2 Мбит/с.',
  'no daily limits. speed restricted to 2 mbps if total consumption exceeds 60 gb':'Без ежедневных лимитов. При расходе свыше 60 ГБ скорость снижается до 2 Мбит/с.',
  'no daily limits. speed restricted to 2 mbps if total consumption exceeds 90 gb':'Без ежедневных лимитов. При расходе свыше 90 ГБ скорость снижается до 2 Мбит/с.',
  // Wordings not currently returned by either catalogue, added ahead of time so
  // a provider-side change cannot leak English into the UI.
  'no speed restrictions':'Без ограничений скорости.',
  'no speed restriction':'Без ограничений скорости.',
  'unlimited at reduced speed':'После исчерпания лимита скорость снижается.',
  'unlimited data at reduced speed':'После исчерпания лимита скорость снижается.',
  'no throttling':'Скорость не снижается.',
  'throttled after limit':'После исчерпания лимита скорость снижается.',
  'fair usage policy applies':'Действует политика справедливого использования.',
  'fair usage policy':'Действует политика справедливого использования.',
  'unlimited':'Безлимитный трафик.',
  'unlimited data':'Безлимитный трафик.',
  'high speed':'Высокая скорость.',
  'high-speed data':'Трафик на высокой скорости.',
  'reduced speed':'Сниженная скорость.',
  'data only':'Только мобильный интернет, без звонков и SMS.',
  'data-only':'Только мобильный интернет, без звонков и SMS.',
  'daily limit':'Действует дневной лимит трафика.',
  'no daily limits':'Без ежедневных лимитов трафика.',
  'no daily limit':'Без ежедневных лимитов трафика.',
  // Explicit "no data" markers - never shown
  'n/a':'',
  'unknown':'',
  '-':''
};
const TARIFF_SPEED_UNITS_RU = {kbps:'Кбит/с',mbps:'Мбит/с',gbps:'Гбит/с'};
/* --- END TARIFF WORDING --- */

/* --------------------------------------------------------------------------
 * Configuration
 * ----------------------------------------------------------------------- */

/* --------------------------------------------------------------------------
 * The two endpoints
 *
 * This used to be one constant and a comment saying a second one must never be
 * added: RU networks reached api.magicesim.store 3/3 and the origin 0/3, so a
 * direct fallback would have been invisible in testing and broken for exactly
 * the customers this app serves.
 *
 * That measurement was taken through a browser on a plain RU connection. The
 * Mini App is not that. It runs inside Telegram's WebView on a phone whose VPN
 * is system-wide, so the WebView's traffic takes the tunnel too — and measured
 * there, on the owner's iPhone on 2026-08-18, the picture inverts:
 *
 *              /health              catalogue 604KB
 *   Render     8/8  p50   237ms     4/4  p50  654ms
 *   Yandex     2/8  p50 12239ms     4/4  p50 1720ms   (AbortError / 502)
 *
 * So for THIS surface the gateway is the fallback, not the road. The storefront
 * keeps the old arrangement, because a browser on a plain connection is still
 * the network the old measurement describes.
 *
 * Both hosts terminate at the same Render backend — /api/v1/status reports the
 * same commit through either — so there is one database, one session table and
 * one set of rules. A token minted through one is valid at the other because it
 * is the same row, and the TMA limiters key on identity (initData fingerprint,
 * telegram user, customer) rather than on IP, so which road it arrives by
 * changes nothing about them.
 * ----------------------------------------------------------------------- */

const API_RENDER = 'https://esim-backend-3wmu.onrender.com';
const API_GATEWAY = 'https://api.magicesim.store';

// Ordered. The client walks this list and stops at the first endpoint that
// returns a VERDICT — not the first that returns success. See shouldFailOver.
const API_ENDPOINTS = [
  { name: 'render', base: API_RENDER },
  { name: 'yandex_fallback', base: API_GATEWAY },
];

// Kept for the storefront and for anything that still expects one base.
const API_BASE = API_GATEWAY;

// Reads: three attempts total. The first retry catches a dropped connection, the
// second catches a bad few seconds. A third would mostly add latency to an
// outage a human can already see.
const READ_ATTEMPTS = 3;
const READ_BACKOFF_MS = [400, 1200];

// Writes get ONE retry and only when a key makes it safe to repeat.
const WRITE_ATTEMPTS_WITH_KEY = 2;
const WRITE_BACKOFF_MS = [700];

// The session mint gets a read's budget, because the whole app is blocked behind
// it and a cold gateway reliably burns the first attempt. See openSession.
const SESSION_ATTEMPTS = 3;
const SESSION_BACKOFF_MS = [600, 1500];

// Longer than the gateway's own ~12s retry budget would take to exhaust, so a
// slow-but-alive request is not abandoned by the client first; short enough that
// a hung one does not become a spinner nobody can dismiss.
const REQUEST_TIMEOUT_MS = 20000;
// The snapshot is same-origin on a CDN. If it has not answered in this long it
// is not going to, and it must not be allowed to hold the first paint hostage.
const STATIC_CATALOGUE_TIMEOUT_MS = 6000;

/* --------------------------------------------------------------------------
 * Small helpers
 * ----------------------------------------------------------------------- */

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Bytes -> GB for display. null stays null: unknown is not zero. */
function gb(bytes) {
  if (bytes === null || bytes === undefined || bytes === '') return null;
  const n = Number(bytes);
  if (!Number.isFinite(n) || n < 0) return null;

  return Math.round((n / (1024 ** 3)) * 100) / 100;
}

/**
 * A price for a Russian customer: whole roubles, grouped, sign after.
 *
 * Non-breaking spaces, written as ESCAPES rather than typed. A price that wraps
 * between its digits — or away from its sign — is a price somebody misreads, and
 * a literal space character in source is invisible in review and easy for an
 * editor to normalise into something else. This started life as U+2009 THIN
 * SPACE, which is breakable in some renderers.
 */
function money(rub) {
  // Absence before coercion, for the third time in this file: Number(null) is 0,
  // so a missing price would render as "0 ₽" — a free eSIM, confidently offered.
  if (rub === null || rub === undefined || rub === '') return '';

  const n = Number(rub);
  if (!Number.isFinite(n)) return '';

  const grouped = Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, '\u00A0');

  return `${grouped}\u00A0\u20BD`;
}

/**
 * Days left, floored, never negative.
 *
 * Floored rather than rounded on purpose: telling somebody they have "1 day"
 * when 4 hours remain is the error that gets a customer stranded.
 */
function daysLeft(expiresAt, now = Date.now()) {
  if (!expiresAt) return null;
  const t = new Date(expiresAt).getTime();
  if (!Number.isFinite(t)) return null;

  return Math.max(0, Math.floor((t - now) / 86400000));
}

/**
 * How much of the bundle is left, 0..1, or null when unknown.
 *
 * Returns null — not 0 — when either side is missing, so a progress bar can
 * render "unknown" instead of an empty tank.
 */
function remainingFraction(esim) {
  // `Number(null)` is 0, not NaN — which is exactly how "we could not ask the
  // provider" turns into "you have nothing left". So absence is checked BEFORE
  // coercion, on both sides.
  const rawTotal = esim ? esim.total_gb : null;
  const rawLeft = esim ? esim.remaining_gb : null;
  if (rawTotal === null || rawTotal === undefined || rawTotal === '') return null;
  if (rawLeft === null || rawLeft === undefined || rawLeft === '') return null;

  const total = Number(rawTotal);
  const left = Number(rawLeft);
  if (!Number.isFinite(total) || total <= 0) return null;
  if (!Number.isFinite(left)) return null;

  return Math.max(0, Math.min(1, left / total));
}

/* --------------------------------------------------------------------------
 * Idempotency keys
 * ----------------------------------------------------------------------- */

/**
 * One key per purchase INTENT, not per request.
 *
 * The distinction is the whole mechanism. A double tap, a retry after a timeout
 * and a resumed screen are all the same intent and must carry the same key, or
 * the customer pays twice. Choosing a different tariff is a new intent and must
 * carry a new one, or the second purchase silently replays the first.
 *
 * The key is derived from what identifies the intent and kept in sessionStorage
 * so it survives the Mini App being backgrounded mid-payment — which is exactly
 * what happens, because paying leaves Telegram for a browser and comes back.
 */
function purchaseIntentKey(intent, storage, randomHex) {
  const scope = [
    'buy',
    String((intent && intent.package_id) || ''),
    String((intent && intent.payment_type) || ''),
    String((intent && intent.promo_code) || '').trim().toUpperCase(),
    String((intent && intent.email) || '').trim().toLowerCase(),
  ].join('|');

  const slot = `mesim.idem.${hash32(scope)}`;
  const existing = storage && storage.getItem ? storage.getItem(slot) : null;
  if (existing) return existing;

  const fresh = `tma-${hash32(scope)}-${randomHex(8)}`;
  if (storage && storage.setItem) storage.setItem(slot, fresh);

  return fresh;
}

/** Forget an intent's key, so the next purchase of the same tariff is a new one. */
function clearIntentKey(intent, storage) {
  const scope = [
    'buy',
    String((intent && intent.package_id) || ''),
    String((intent && intent.payment_type) || ''),
    String((intent && intent.promo_code) || '').trim().toUpperCase(),
    String((intent && intent.email) || '').trim().toLowerCase(),
  ].join('|');
  if (storage && storage.removeItem) storage.removeItem(`mesim.idem.${hash32(scope)}`);
}

/** Tiny stable hash. Not security — a storage slot name. */
function hash32(text) {
  let h = 2166136261;
  const s = String(text);
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }

  return (h >>> 0).toString(36);
}

/* --------------------------------------------------------------------------
 * The API client
 * ----------------------------------------------------------------------- */

class ApiError extends Error {
  constructor(status, code, message, body) {
    super(message || code || `HTTP ${status}`);
    this.name = 'ApiError';
    this.status = status;
    this.code = code || '';
    this.body = body || null;
  }

  /** The session is gone and the app must mint a new one from initData. */
  get isAuthFailure() {
    return this.status === 401;
  }

  /**
   * The request never reached a decision — a gateway drop, a timeout, an offline
   * radio. Safe to retry for a read; for a write, only with a key.
   */
  get isTransport() {
    return this.status === 0 || this.status === 502 || this.status === 503 || this.status === 504;
  }
}

/**
 * @param {object} deps
 * @param {Function} deps.fetch      window.fetch, or a stub
 * @param {object}   deps.storage    sessionStorage-like
 * @param {Function} [deps.now]
 * @param {Function} [deps.sleep]
 * @param {Function} [deps.randomHex]
 */
function createApi(deps = {}) {
  const doFetch = deps.fetch;
  const storage = deps.storage || memoryStorage();
  const now = deps.now || (() => Date.now());
  const wait = deps.sleep || sleep;
  const randomHex = deps.randomHex || defaultRandomHex;
  // A single `base` still works (the storefront passes one); otherwise the
  // ordered endpoint list drives failover.
  const endpoints = deps.endpoints
    || (deps.base ? [{ name: 'custom', base: deps.base }] : API_ENDPOINTS);
  const telemetry = typeof deps.telemetry === 'function' ? deps.telemetry : () => {};

  // Held in memory only. Writing a bearer to localStorage would leave it on the
  // device after the app closes, and it is re-mintable from initData for free.
  let sessionToken = null;
  let sessionExpiresAt = 0;

  async function once(path, { method = 'GET', body = null, auth = true, base = endpoints[0].base } = {}) {
    const controller = typeof AbortController === 'function' ? new AbortController() : null;
    const timer = controller ? setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS) : null;

    try {
      const res = await doFetch(base + path, {
        method,
        headers: Object.assign(
          { 'Content-Type': 'application/json', Accept: 'application/json' },
          auth && sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}
        ),
        body: body === null ? undefined : JSON.stringify(body),
        signal: controller ? controller.signal : undefined,
      });

      const text = await res.text();
      let json = null;
      try { json = text ? JSON.parse(text) : null; } catch { json = null; }

      if (!res.ok) {
        throw new ApiError(res.status, json && json.error, json && json.message, json);
      }

      return json;
    } catch (err) {
      if (err instanceof ApiError) throw err;
      // A thrown fetch is a transport failure: DNS, TLS, offline, abort. Status 0
      // so `isTransport` treats it like the gateway drop it usually is.
      throw new ApiError(0, 'NETWORK', 'network unavailable', null);
    } finally {
      if (timer) clearTimeout(timer);
    }
  }

  /**
   * One request, with the retry policy the method deserves.
   *
   * A 401 is retried exactly once, after re-authenticating — a 30-minute session
   * expiring while the app sits open is the single most likely failure here, and
   * making the customer notice it would be pointless.
   */
  /**
   * May this failure be carried to the other endpoint?
   *
   * ONLY a transport failure — status 0 (abort, DNS, TLS, offline), 502, 503,
   * 504 — means "this road did not reach a verdict". Everything else is an
   * answer, and an answer must be honoured wherever it came from.
   *
   * This is the whole safety of the design. A 401 re-asked at the other host is
   * still a 401 and merely doubles the delay; a 409 or a 422 re-asked is worse,
   * because the second host may be a moment behind and give a different reply to
   * a question already settled. Both endpoints are the same database — asking it
   * twice does not make the answer truer.
   */
  function shouldFailOver(err) {
    return Boolean(err && err.isTransport);
  }

  /**
   * One logical request, across the endpoint list.
   *
   * Bounded twice over: each endpoint gets its own small attempt budget, and
   * there are exactly two endpoints. Worst case is attempts×endpoints requests
   * and then a thrown error — never a loop that keeps a customer waiting on a
   * network that is not coming back.
   */
  async function request(path, opts = {}) {
    const isWrite = opts.method && opts.method !== 'GET';
    const retryable = !isWrite || Boolean(opts.idempotent);
    const attempts = isWrite
      ? (opts.idempotent ? WRITE_ATTEMPTS_WITH_KEY : 1)
      : READ_ATTEMPTS;
    const backoff = isWrite ? WRITE_BACKOFF_MS : READ_BACKOFF_MS;

    let lastError = null;
    let reauthed = false;
    let primaryMs = null;

    for (let e = 0; e < endpoints.length; e += 1) {
      const endpoint = endpoints[e];
      const startedAt = now();

      for (let attempt = 0; attempt < attempts; attempt += 1) {
        try {
          const out = await once(path, { ...opts, base: endpoint.base });
          telemetry({
            api_route: endpoint.name,
            path,
            primary_latency_ms: primaryMs,
            latency_ms: now() - startedAt,
            fallback_used: e > 0,
            fallback_reason: e > 0 ? (lastError && (lastError.code || `http_${lastError.status}`)) : null,
          });

          return out;
        } catch (err) {
          lastError = err;

          if (err.isAuthFailure && !reauthed && opts.auth !== false && deps.reauthenticate) {
            reauthed = true;
            await deps.reauthenticate();
            continue;                      // does not consume an attempt
          }

          // An answer, not an outage: stop everywhere, not just here.
          if (!shouldFailOver(err)) {
            telemetry({
              api_route: endpoint.name,
              path,
              primary_latency_ms: primaryMs,
              latency_ms: now() - startedAt,
              fallback_used: e > 0,
              fallback_reason: null,
              refused: err.status || 0,
            });
            throw err;
          }

          // A write with no key may not be repeated anywhere — not on this
          // endpoint and not on the other one. It may already have been applied.
          if (!retryable) throw err;

          if (attempt < attempts - 1) await wait(backoff[Math.min(attempt, backoff.length - 1)]);
        }
      }

      if (e === 0) primaryMs = now() - startedAt;
    }

    telemetry({
      api_route: 'none',
      path,
      primary_latency_ms: primaryMs,
      fallback_used: endpoints.length > 1,
      fallback_reason: lastError && (lastError.code || `http_${lastError.status}`),
      failed: true,
    });

    throw lastError;
  }

  /* ---- session ---- */

  /**
   * Mint a session from initData.
   *
   * This is the one request the entire app waits on, and until 2026-08-17 it was
   * the only one in the file with no retry at all — `once`, one shot. A cold
   * gateway (TD-55) answers the first call after an idle period with a 502 about
   * twelve seconds in; measured 2026-08-17, five of six cold probes did exactly
   * that while the same instance then served 401s in 0.2s. One such 502 killed
   * the Mini App outright: no session, no catalogue, nothing to tap (R-44).
   *
   * Reads get three attempts for weaker reasons. So does this now.
   *
   * Retrying is safe: minting is not a purchase. It writes a session row and
   * touches no order, payment or provider, so the worst case of a retried cold
   * start is two short-lived rows where one was wanted.
   */
  async function openSession(initData) {
    let lastError = null;
    let primaryMs = null;

    for (let e = 0; e < endpoints.length; e += 1) {
      const endpoint = endpoints[e];
      const startedAt = now();

      for (let attempt = 0; attempt < SESSION_ATTEMPTS; attempt += 1) {
        try {
          const out = await once('/api/v1/tma/session', {
            method: 'POST', body: { init_data: initData }, auth: false, base: endpoint.base,
          });
          sessionToken = out.session_token;
          sessionExpiresAt = now() + (Number(out.expires_in) || 0) * 1000;
          telemetry({
            api_route: endpoint.name,
            path: '/api/v1/tma/session',
            primary_latency_ms: primaryMs,
            latency_ms: now() - startedAt,
            fallback_used: e > 0,
            fallback_reason: e > 0 ? (lastError && (lastError.code || `http_${lastError.status}`)) : null,
          });

          return out;
        } catch (err) {
          lastError = err;
          // A rejected initData is a verdict, not a blip: 401 means the
          // signature did not check out, and the other endpoint verifies it
          // against the same bot token and the same clock. Asking twice only
          // doubles the wait before telling the customer the same thing.
          if (!shouldFailOver(err)) throw err;

          if (attempt < SESSION_ATTEMPTS - 1) {
            await wait(SESSION_BACKOFF_MS[Math.min(attempt, SESSION_BACKOFF_MS.length - 1)]);
          }
        }
      }

      if (e === 0) primaryMs = now() - startedAt;
    }

    throw lastError;
  }

  const hasSession = () => Boolean(sessionToken) && now() < sessionExpiresAt;

  /* ---- catalogue (public, no session) ---- */

  // The same endpoint the website uses. §8.3 rejected a TMA twin of it, so this
  // is deliberately not a Mini-App-specific catalogue.
  const catalogue = () => request('/api/v1/retail/packages', { auth: false });

  /**
   * The catalogue snapshot that ships with the site.
   *
   * Same origin, served by the Pages CDN, refreshed six times a day by CI — so
   * it neither waits for Render nor for the gateway, and it is the one path
   * that still works when both are unreachable. Prices in it are up to four
   * hours old, which is why anything drawn from it must say so (§9 S1: showing
   * a stale catalogue as fresh is not acceptable, because a price is a promise).
   *
   * Deliberately NOT routed through `request`: it is not an API call, it has no
   * endpoint to fail over to, and one attempt is the whole budget it deserves.
   */
  async function staticCatalogue() {
    // One attempt is the whole budget — but an attempt with no deadline is not
    // a budget. A CDN request that hangs used to leave the catalogue skeleton
    // on screen forever, because the caller awaits this promise and nothing
    // else was ever going to settle it.
    const ac = typeof AbortController === 'function' ? new AbortController() : null;
    const timer = ac ? setTimeout(() => ac.abort(), STATIC_CATALOGUE_TIMEOUT_MS) : null;

    let res;
    try {
      res = await doFetch('../assets/catalog.json', {
        headers: { Accept: 'application/json' },
        signal: ac ? ac.signal : undefined,
      });
    } finally {
      if (timer) clearTimeout(timer);
    }
    if (!res.ok) throw new ApiError(res.status, 'STATIC_CATALOGUE', 'snapshot unavailable', null);
    const json = await res.json();

    // Normalised to the live envelope so no caller has to know where it came from.
    return {
      status: 'success',
      count: json.package_count || (json.packages || []).length,
      currency: 'RUB',
      data: json.packages || [],
      generated_at: json.generated_at || null,
    };
  }

  /* ---- the customer's own things ---- */

  const me = () => request('/api/v1/tma/me');
  const orders = (params = '') => request(`/api/v1/tma/me/orders${params}`);
  const activeOrders = () => request('/api/v1/tma/me/orders/active');

  /**
   * What this eSIM could be topped up with.
   *
   * A GET, and read-only on the server too: it creates no intent and calls no
   * provider write. The answer carries `purchase_enabled`, which is how the
   * app learns that real options exist while buying one is not open yet — the
   * client is told rather than finding out at a payment step that refuses.
   *
   * A 404 here is an eSIM that is not ours or does not exist; the server
   * answers both identically on purpose, so this does not try to tell them
   * apart either.
   */
  const topups = (esimId) => request(`/api/v1/tma/esims/${encodeURIComponent(esimId)}/topups`);

  /* ---- S13: purchases made on the website ---- */

  /**
   * Ask for a code. The answer is the SAME whatever happened — sent, rate
   * limited, malformed, already someone else's — so this function has nothing
   * to branch on and deliberately offers none.
   */
  const requestEmailCode = (email) => request('/api/v1/tma/identity/email/request', {
    method: 'POST', body: { email },
  });

  /**
   * Confirm it. This one CAN fail meaningfully: the person holding the session
   * already proved they asked, so «wrong code» and «expired» are worth telling
   * apart — one means retype, the other means start over.
   */
  const confirmEmailCode = (email, code) => request('/api/v1/tma/identity/email/confirm', {
    method: 'POST', body: { email, code },
  });
  const orderStatus = (token) => request(`/api/v1/tma/orders/${encodeURIComponent(token)}/status`);
  const esims = () => request('/api/v1/tma/esims');
  const esim = (id) => request(`/api/v1/tma/esims/${encodeURIComponent(id)}`);

  // POST, but it creates nothing — see the route comment. Retryable as a read is
  // wrong (it is a POST), so it gets the write policy without a key: one shot.
  const activation = (id) => request(
    `/api/v1/tma/esims/${encodeURIComponent(id)}/activation`, { method: 'POST', body: {} }
  );

  const refreshUsage = (id) => request(
    `/api/v1/tma/esims/${encodeURIComponent(id)}/usage/refresh`, { method: 'POST', body: {} }
  );

  /**
   * Buy. The only call in this file that can spend money.
   *
   * `idempotent: true` is what makes the single retry safe, and the key comes
   * from the INTENT rather than from this call — so a retry, a double tap and a
   * resumed screen all reuse it.
   */
  async function purchase(intent) {
    const key = purchaseIntentKey(intent, storage, randomHex);

    return request('/api/v1/tma/orders', {
      method: 'POST',
      idempotent: true,
      body: {
        package_id: intent.package_id,
        email: intent.email,
        payment_type: intent.payment_type,
        // Reported, never asserted. This was hardcoded `true`, which sent an
        // acceptance the customer had not given — §9 S4 and §14.6 both require
        // an explicit act, and a pre-ticked box is expressly not one. The
        // checkout will not enable its pay button until the box is ticked, so a
        // false here means something went wrong and the server should refuse.
        terms_accepted: intent.terms_accepted === true,
        promo_code: intent.promo_code || undefined,
        // An assertion about what was shown, never an instruction. The server
        // prices the order and refuses if this disagrees.
        expected_amount_rub: intent.expected_amount_rub,
        idempotency_key: key,
      },
    });
  }

  return {
    openSession, hasSession, catalogue, staticCatalogue, me, orders, activeOrders, orderStatus,
    topups, requestEmailCode, confirmEmailCode,
    esims, esim, activation, refreshUsage, purchase,
    forgetIntent: (intent) => clearIntentKey(intent, storage),
    get token() { return sessionToken; },
  };
}

/* --------------------------------------------------------------------------
 * A read-through cache that is honest about staleness
 * ----------------------------------------------------------------------- */

/**
 * Serve the last good answer when the network will not cooperate.
 *
 * This is the concrete answer to TD-55 in the UI: a customer who opens "my
 * eSIMs" on a bad minute sees their eSIMs with a quiet "shown from cache" line,
 * not an error and not a spinner. What it must never do is hide a failure on a
 * WRITE, so only reads go through here.
 */
function createCache(storage, { now = () => Date.now() } = {}) {
  const KEY = (name) => `mesim.cache.${name}`;

  return {
    read(name, maxAgeMs) {
      try {
        const raw = storage.getItem(KEY(name));
        if (!raw) return null;
        const parsed = JSON.parse(raw);
        const age = now() - Number(parsed.at || 0);
        if (maxAgeMs && age > maxAgeMs) return { value: parsed.value, age, expired: true };

        return { value: parsed.value, age, expired: false };
      } catch {
        return null;
      }
    },
    write(name, value) {
      try {
        storage.setItem(KEY(name), JSON.stringify({ at: now(), value }));
      } catch {
        // A full or disabled storage must not break the app. Losing the cache
        // costs a spinner; throwing here costs the screen.
      }
    },
  };
}

/**
 * Fetch, and fall back to cache with the staleness made visible.
 *
 * Returns { value, stale, error } so a caller cannot accidentally present cached
 * data as fresh — the flag is in the same object as the data.
 */
async function readThrough(cache, name, fetcher) {
  try {
    const value = await fetcher();
    cache.write(name, value);

    return { value, stale: false, error: null };
  } catch (err) {
    const cached = cache.read(name);
    if (cached) return { value: cached.value, stale: true, error: err, age: cached.age };

    return { value: null, stale: false, error: err };
  }
}

/* --------------------------------------------------------------------------
 * Catalogue shaping — done here so the UI stays dumb
 * ----------------------------------------------------------------------- */

/**
 * Group the flat package list by country, and pick a "best value" per country.
 *
 * Best value is cheapest-per-GB among the cheapest half, not simply the cheapest
 * plan: the 1 GB option is almost always cheapest and almost never what somebody
 * travelling for a week wants.
 */
/**
 * Russian names for the multi-country families the provider ships.
 *
 * These are NOT countries and have no ISO code, so they cannot come from the
 * generated dictionary: three arrive with invented codes (`AF-29`, `CA-4`,
 * `GL-120`) and the rest are filed under whichever member country sorts first,
 * which is why "Vietnam Plus" was shelved under Indonesia. Keyed on the English
 * family name because that is the stable part of the provider's title — the
 * volume and duration suffix varies per package.
 *
 * A family missing here falls back to naming itself by its coverage ("Регион ·
 * 6 стран"), which is honest rather than technical. It never shows the code.
 */
const REGION_NAMES = Object.freeze({
  'EU': 'Европа',
  'EUCONNECT': 'Европа',
  'EUROPE AND USA': 'Европа и США',
  'AFRICA': 'Африка',
  'CARIBBEAN': 'Карибские острова',
  'BEST WORLD': 'Весь мир',
  'HALF GLOBAL': 'Полмира',
  'GLOBAL': 'Весь мир',
  'LATAM': 'Латинская Америка',
  'APAC': 'Азия и Океания',
  'AUSTRALIA AND NZ': 'Австралия и Новая Зеландия',
  'CENTRAL ASIA': 'Центральная Азия',
  'CHINA KOREA JAPAN': 'Китай, Корея и Япония',
  'GREATER CHINA AND TAIWAN PREMIUM': 'Большой Китай и Тайвань',
  'GREECE CYPRUS TURKEY': 'Греция, Кипр и Турция',
  'JERSEY GUERNSEY AND IOM': 'Джерси, Гернси и Мэн',
  'VIETNAM PLUS': 'Вьетнам и Юго-Восточная Азия',
  'SINGAPORE MALAYSIA AND THAILAND': 'Сингапур, Малайзия и Таиланд',
  'SPAIN AND PORTUGAL': 'Испания и Португалия',
  'ITALY': 'Италия',
});

/** Russian country name, or the code if we somehow have none. Never blank. */
function countryLabel(code) {
  const key = String(code || '').toUpperCase();
  return countryNames[key] || key;
}

/** The flag the catalogue already carries, or one derived from the ISO code. */
function flagFor(code, pkg) {
  if (pkg && pkg.coverage_flags && String(pkg.coverage_flags).trim()) {
    // Regional packages carry a whole string of them; one flag is a label, ten
    // are noise on a 375px screen.
    const flags = [...String(pkg.coverage_flags).trim()];
    if (flags.length <= 4) return String(pkg.coverage_flags).trim();
  }
  const key = String(code || '').toUpperCase();
  if (!/^[A-Z]{2}$/.test(key)) return '';

  return key.replace(/[A-Z]/g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

/** A package covering more than one country is a regional offer, not a local one. */
function isRegional(pkg) {
  return Array.isArray(pkg && pkg.coverage_country_codes) && pkg.coverage_country_codes.length > 1;
}

/** "3 тарифа" — Russian needs three forms and "1 тарифов" reads as a bug. */
function plural(n, one, few, many) {
  const abs = Math.abs(Number(n) || 0);
  const mod10 = abs % 10;
  const mod100 = abs % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;

  return many;
}

const tariffWord = (n) => `${n} ${plural(n, 'тариф', 'тарифа', 'тарифов')}`;
const countryWord = (n) => `${n} ${plural(n, 'страна', 'страны', 'стран')}`;

/** The provider's family name, normalised to a REGION_NAMES key. */
function regionKey(pkg) {
  return String((pkg && pkg.name) || '')
    .replace(/\s*\d+\s*GB[\s\S]*$/i, '')     // "Africa 5GB 30Days" -> "Africa"
    .replace(/\s*\(\d+\+?\s*areas?\)/i, '')  // "Global (120+ areas)" -> "Global"
    .replace(/\s+Unlimited[\s\S]*$/i, '')    // "EUconnect Unlimited 7 Days" -> "EUconnect"
    .replace(/\s+Premium$/i, ' Premium')
    .trim()
    .toUpperCase();
}

function regionLabel(pkg) {
  const named = REGION_NAMES[regionKey(pkg)];
  if (named) return named;
  const n = (pkg && pkg.coverage_country_codes && pkg.coverage_country_codes.length) || 0;

  return n ? `Регион · ${countryWord(n)}` : 'Регион';
}

function byCountry(packages) {
  const map = new Map();
  for (const p of (Array.isArray(packages) ? packages : [])) {
    // A catalogue is external input. One malformed row must cost that row, not
    // the screen.
    if (!p || typeof p !== 'object') continue;
    const code = String(p.country_code || '').toUpperCase();
    if (!code) continue;
    if (!map.has(code)) {
      map.set(code, {
        country_code: code,
        country: countryLabel(code),
        flag: flagFor(code, p),
        items: [],
      });
    }
    map.get(code).items.push(p);
  }

  for (const group of map.values()) {
    group.items.sort((a, b) => Number(a.price) - Number(b.price));
    group.from = group.items.length ? Number(group.items[0].price) : null;
    group.best = pickBestValue(group.items);
  }

  return [...map.values()].sort((a, b) => String(a.country).localeCompare(String(b.country), 'ru'));
}

/**
 * S1's data model: local destinations and regional offers are different things
 * and the Blueprint lists them as separate sections (§9 S1, items 4 and 5).
 *
 * Splitting them also fixes a lie the flat grouping told. A regional package is
 * filed under one member country, so "Vietnam Plus" — six countries — appeared
 * as an Indonesian tariff, and "EU" (34 countries) as an Andorran one.
 */
function groupCatalogue(packages) {
  const rows = (Array.isArray(packages) ? packages : []).filter((p) => p && typeof p === 'object');
  const local = rows.filter((p) => !isRegional(p));
  const wide = rows.filter(isRegional);

  const regions = new Map();
  for (const p of wide) {
    const label = regionLabel(p);
    if (!regions.has(label)) {
      regions.set(label, {
        country_code: String(p.country_code || '').toUpperCase(),
        country: label,
        // A handful of flags still reads as a place; twenty-nine of them is a
        // smear, and a globe says "region" better than a truncated list.
        flag: (p.coverage_country_codes || []).length <= 3
          ? flagFor(p.country_code, p)
          : '🌍',
        regional: true,
        coverage: (p.coverage_country_codes || []).slice(),
        items: [],
      });
    }
    const g = regions.get(label);
    g.items.push(p);
    // Keep the widest coverage we have seen for this family: the customer is
    // choosing a region, and the honest count is the biggest one it sells.
    if ((p.coverage_country_codes || []).length > g.coverage.length) {
      g.coverage = p.coverage_country_codes.slice();
    }
  }

  const finish = (g) => {
    g.items.sort((a, b) => Number(a.price) - Number(b.price));
    g.from = g.items.length ? Number(g.items[0].price) : null;
    g.best = pickBestValue(g.items);

    return g;
  };

  return {
    countries: byCountry(local),
    regions: [...regions.values()].map(finish)
      .sort((a, b) => (b.coverage.length - a.coverage.length)),
  };
}

/**
 * Regional offers that cover a given country.
 *
 * Blueprint §9 S2: a country with no local tariff is "не ошибка, а тупик, из
 * которого нужен выход" — and even where local tariffs exist, a traveller
 * crossing borders is better served by knowing the regional one exists.
 */
function regionsCovering(regions, code) {
  const key = String(code || '').toUpperCase();

  return (regions || [])
    .filter((r) => (r.coverage || []).some((c) => String(c).toUpperCase() === key))
    .sort((a, b) => Number(a.from) - Number(b.from));
}

function pickBestValue(items) {
  const usable = (items || []).filter((p) => Number(p.data_gb) > 0 && Number(p.price) > 0);
  if (!usable.length) return null;
  const scored = usable
    .map((p) => ({ p, perGb: Number(p.price) / Number(p.data_gb) }))
    .sort((a, b) => a.perGb - b.perGb);

  return scored[0].p;
}

/** Free-text country search that tolerates the way people actually type. */
/**
 * Fold a string down to something two people typing the same country will agree
 * on: case, surrounding space, ё/е, and the composed/decomposed forms macOS and
 * Android keyboards disagree about for й.
 */
function normalize(text) {
  return String(text == null ? '' : text)
    .normalize('NFC')
    .toLowerCase()
    .replace(/ё/g, 'е')
    // й -> и is not pedantry. The country is spelled «Таиланд», but a great many
    // people type «Тайланд», and «тай» — the obvious short form — matches
    // neither without this fold. It also makes «Йемен»/«Иемен» agree.
    .replace(/й/g, 'и')
    .replace(/[‐-―]/g, '-')  // ‑ – — typed by iOS autocorrect
    .trim();
}

/**
 * Free-text search that tolerates the way people actually type.
 *
 * Matches the Russian name, the Latin slug, and — last — the ISO code. The slug
 * is why "thailand" and "uae" work at all: the list is in Russian, and somebody
 * already abroad may well be on a Latin keyboard. The code is accepted because
 * it costs nothing and someone will try it, but it is never a display value and
 * never the reason a row is offered first.
 */
function searchCountries(groups, query) {
  const q = normalize(query);
  if (!q) return groups;

  // Ranked, not merely filtered. «тай» legitimately matches both «Таиланд» and
  // «Ки-тай»; which one is offered first is the whole difference between search
  // that works and search that technically works.
  //
  //   0  the name starts with what was typed
  //   1  the Latin slug starts with it
  //   2  the name or slug contains it
  //   3  a regional group whose coverage contains a match
  //   4  the ISO code — accepted, never promoted
  const rank = (g) => {
    const name = normalize(g.country);
    const code = String(g.country_code || '').toUpperCase();
    const slug = normalize(countryLatin[code] || '').replace(/-/g, ' ');
    const ql = q.replace(/-/g, ' ');

    if (name.startsWith(q)) return 0;
    // A regional group is filed under one member country, so it carries that
    // country's code and slug — «Большой Китай и Тайвань» is stored under CN.
    // Letting it match on those made "china" offer the region above China
    // itself. A region earns its place by its own name or by its coverage.
    if (!g.regional) {
      if (slug && slug.startsWith(ql)) return 1;
      if (name.includes(q) || slug && slug.includes(ql)) return 2;
    } else if (name.includes(q)) {
      return 2;
    }
    if (g.regional && (g.coverage || []).some((c) => {
      const cc = String(c).toUpperCase();
      const cs = normalize(countryLatin[cc] || '');
      return normalize(countryLabel(cc)).includes(q) || (cs && cs.includes(ql));
    })) return 3;
    if (!g.regional && code.toLowerCase().startsWith(q)) return 4;

    return -1;
  };

  const popularity = new Map(popularCountries.map((c, i) => [c, i]));

  return groups
    .map((g) => ({ g, r: rank(g) }))
    .filter((x) => x.r >= 0)
    .sort((a, b) => a.r - b.r
      || (popularity.get(a.g.country_code) ?? 99) - (popularity.get(b.g.country_code) ?? 99)
      || String(a.g.country).localeCompare(String(b.g.country), 'ru'))
    .map((x) => x.g);
}

/**
 * The storefront's popular destinations, in the storefront's order, reduced to
 * the ones we can actually sell today.
 *
 * The order is deliberately NOT re-sorted by price or name: it is an editorial
 * decision that lives on the website, and two surfaces disagreeing about what
 * is popular is worse than either order being imperfect.
 */
function popularGroups(countryGroups) {
  const byCode = new Map((countryGroups || []).map((g) => [g.country_code, g]));

  return popularCountries.map((code) => byCode.get(code)).filter(Boolean);
}

/**
 * §9 S2: «Сортировка: по умолчанию цена по возрастанию; переключатели по цене
 * и по объёму.»
 *
 * Two axes, because they answer two different questions. Price first is the
 * right default — it is what the list is scanned for — but a customer who
 * knows they need 20 GB is looking for volume and should not have to read
 * every card to find where it starts.
 *
 * Unlimited sorts above every finite volume rather than as some large number:
 * it is not a bigger amount, it is a different promise. Ties fall back to
 * price so the order is total and the list never reshuffles on a redraw.
 */
const TARIFF_SORTS = Object.freeze({
  price: { label: 'По цене', key: (p) => Number(p.price) || 0 },
  volume: { label: 'По объёму', key: (p) => (p.unlimited ? Infinity : Number(p.data_gb) || 0) },
});

function sortTariffs(items, sort = 'price') {
  const spec = TARIFF_SORTS[sort] || TARIFF_SORTS.price;
  const list = Array.isArray(items) ? items.slice() : [];
  // Volume descending (more is what is being looked for), price ascending.
  const dir = sort === 'volume' ? -1 : 1;

  return list.sort((a, b) => (dir * (spec.key(a) - spec.key(b)))
    || (Number(a.price) - Number(b.price))
    || String(a.package_id).localeCompare(String(b.package_id)));
}

/**
 * §9 S9: «Отметка времени обязательна ВСЕГДА — и когда данные свежие тоже.»
 *
 * "Осталось 3.2 ГБ" is a claim about a number the provider owns and we merely
 * relayed, possibly hours ago. Without a time next to it, the product is
 * making a promise it does not control. With one, the same number is a fact
 * about when we asked — which is true, and is what a traveller checking their
 * balance in an airport actually needs to know.
 *
 * Relative, because the absolute time answers the wrong question: nobody cares
 * that it was 14:02, only that it was ten minutes ago.
 */
function syncedAgo(iso, now = Date.now()) {
  if (!iso) return 'данные ещё не запрашивались';
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return 'время последней проверки неизвестно';

  const mins = Math.floor((now - t) / 60000);
  if (mins < 0) return 'только что';
  if (mins < 1) return 'обновлено только что';
  if (mins < 60) return `обновлено ${mins} ${plural(mins, 'минуту', 'минуты', 'минут')} назад`;

  const hours = Math.floor(mins / 60);
  if (hours < 24) return `обновлено ${hours} ${plural(hours, 'час', 'часа', 'часов')} назад`;

  const days = Math.floor(hours / 24);

  return `обновлено ${days} ${plural(days, 'день', 'дня', 'дней')} назад`;
}

/**
 * Which set of installation steps to open on.
 *
 * §9 S10 asks for `Telegram.WebApp.platform` rather than the user agent, and
 * the reason is concrete: inside a WebView the UA describes the engine, so an
 * Android tablet running a WebKit-flavoured browser, or any client Telegram
 * has not taught us about, lands on the wrong instructions. Telegram knows
 * which client it is. The manual switch stays either way — detection is
 * allowed to be wrong, a customer stuck on the wrong steps is not.
 */
function installPlatform(tgPlatform, userAgent) {
  const p = String(tgPlatform || '').toLowerCase();
  if (p === 'ios' || p === 'macos') return 'ios';
  if (p === 'android' || p === 'android_x') return 'android';
  // 'tdesktop', 'weba', 'webk', 'unknown' and anything new: Telegram is not
  // telling us about a phone, so fall back to what the browser says.
  if (/iPhone|iPad|iPod/i.test(String(userAgent || ''))) return 'ios';

  return 'android';
}

/* --------------------------------------------------------------------------
 * S3 · what a tariff actually is
 * ----------------------------------------------------------------------- */

/**
 * The same four mappers the storefront renders tariff cards with.
 *
 * Ported rather than reinvented (Blueprint P8). The DATA they read is
 * generated into the block above from assets/country-tariffs.js; only this
 * logic is written here, and it is deliberately identical — an unrecognised
 * provider string is hidden, never printed, and a missing value drops its row
 * instead of being shown with a vague caveat.
 */
const TARIFF_SPEED_ONLY_RE = /^(\d+(?:[.,]\d+)?)\s*(kbps|mbps|gbps)$/i;

/**
 * Network generations ONLY.
 *
 * MobiMatter's `speed` says things like "Unrestricted", which is throughput,
 * not a generation — turning that into a fake 4G would be inventing a claim
 * about the network a customer is buying.
 */
function tariffNetworks(pkg) {
  const src = pkg || {};
  const list = Array.isArray(src.network_technologies) && src.network_technologies.length
    ? src.network_technologies
    : String(src.speed || '').split(/[^0-9A-Za-z]+/);
  const out = [];
  for (const raw of list) {
    let t = String(raw || '').toUpperCase();
    if (t === 'LTE') t = '4G';
    if (!/^[2345]G$/.test(t)) continue;
    if (!out.includes(t)) out.push(t);
  }

  return out.sort().join('/');
}

/** Tri-state. No data drops the row — '' is the caller's signal to omit it. */
function tariffHotspot(pkg) {
  const v = (pkg || {}).hotspot_supported;
  if (v === true) return 'поддерживается';
  if (v === false) return 'не поддерживается';

  return '';
}

/** Whitelist. An unrecognised policy falls back to the usual behaviour. */
function tariffActivation(pkg) {
  const key = String((pkg || {}).activation_policy || '').trim().toLowerCase();

  return Object.prototype.hasOwnProperty.call(TARIFF_ACTIVATION_LABELS, key)
    ? TARIFF_ACTIVATION_LABELS[key]
    : TARIFF_ACTIVATION_FALLBACK;
}

/** Russian, or nothing. An untranslated English string is never rendered. */
function tariffTextRu(raw) {
  const s = String(raw == null ? '' : raw).replace(/\s+/g, ' ').trim();
  if (!s) return '';
  if (/[а-яё]/i.test(s)) return s;

  const key = s.toLowerCase();
  if (Object.prototype.hasOwnProperty.call(TARIFF_TEXT_RU, key)) return TARIFF_TEXT_RU[key];

  const m = s.match(TARIFF_SPEED_ONLY_RE);
  if (m) {
    const unit = TARIFF_SPEED_UNITS_RU[m[2].toLowerCase()];
    if (unit) return `После исчерпания лимита скорость снижается до ${m[1]} ${unit}.`;
  }

  return '';
}

/**
 * The characteristics block of S3 — «только непустые поля».
 *
 * Every row is a fact the provider actually sent. Nothing here has a default,
 * a placeholder or an "уточняется": a row that cannot be filled is a row that
 * is not drawn, because an empty label next to a price is a question, and the
 * point of this screen is to remove questions rather than add them.
 *
 * `sms_supported` and `calls_supported` are shown ONLY on an explicit `true`
 * (§9 S3). They are null on all 974 packages today, so in practice these rows
 * never appear — which is the correct outcome and not a bug to fix. A customer
 * must not leave this screen believing a bank's SMS will arrive on a foreign
 * profile: that is not ours to promise, and the wording below does not.
 */
function tariffFacts(pkg) {
  const p = pkg || {};
  const rows = [];
  const push = (label, value) => { if (value) rows.push({ label, value }); };

  // The site's own «Покрытие и условия» sheet, row for row and label for
  // label (index.html #coverageModal). Two shops describing one tariff with
  // two different vocabularies is how a customer comes to believe they are
  // looking at two different products.
  const gb = Number(p.data_gb);
  push('Объём трафика', p.unlimited ? 'безлимит'
    : (Number.isFinite(gb) && gb > 0 ? `${Number.isInteger(gb) ? gb : String(gb)} ГБ` : ''));

  const days = Number(p.validity_days);
  push('Срок действия', Number.isFinite(days) && days > 0
    ? `${days} ${plural(days, 'день', 'дня', 'дней')}` : '');

  push('Начало срока', tariffActivation(p));
  push('Сеть', tariffNetworks(p));
  push('Раздача интернета', tariffHotspot(p));
  push('Скорость', tariffTextRu(p.speed_note));
  push('После лимита', tariffTextRu(p.fup_policy));

  if (p.calls_supported === true) push('Звонки', 'поддерживаются');
  if (p.sms_supported === true) {
    push('SMS', 'приём SMS поддерживается оператором. Доставка кодов от банков не гарантируется');
  }
  if (p.data_only === true) push('Только интернет', 'звонков и SMS нет');

  return rows;
}

/**
 * The site puts «Покрытие» at the top of the same sheet, as one line rather
 * than a country list — «Азия и Океания, 34 страны» reads in a second where
 * thirty-four chips do not. The full list stays one tap away underneath.
 */
function coverageSummary(pkg) {
  const p = pkg || {};
  const codes = [...new Set(Array.isArray(p.coverage_country_codes) ? p.coverage_country_codes : [])];
  if (codes.length <= 1) return countryLabel(codes[0] || p.country_code);

  const named = REGION_NAMES[regionKey(p)];

  return named ? `${named}, ${countryWord(codes.length)}` : countryWord(codes.length);
}

/** §9 S3: «что произойдёт после оплаты» — three steps, one line each. */
const AFTER_PAYMENT_STEPS = Object.freeze([
  'Оплата откроется в браузере — вернитесь в Telegram, мы покажем статус.',
  'Мы выпустим eSIM у оператора, обычно меньше чем за минуту.',
  'QR и код установки появятся в «Мои eSIM» — установите до поездки.',
]);

/**
 * §9 S8: «активные сверху, истёкшие ниже и приглушены».
 *
 * The server returns newest-first, which is the wrong axis: a customer opens
 * this list on a trip, and the eSIM they are travelling on is the one that
 * must be at the top even if it was bought a year before the souvenir one.
 *
 * Stable within each band — the server's order is preserved — so this only
 * ever moves spent eSIMs down, never shuffles live ones among themselves.
 */
const SPENT_ESIM_STATUSES = Object.freeze(['expired', 'depleted', 'failed']);

const isSpentEsim = (e) => SPENT_ESIM_STATUSES.includes(e && e.status);

function sortOwnedEsims(items) {
  const list = Array.isArray(items) ? items.slice() : [];

  return list
    .map((e, i) => ({ e, i }))
    .sort((a, b) => (Number(isSpentEsim(a.e)) - Number(isSpentEsim(b.e))) || (a.i - b.i))
    .map((x) => x.e);
}

/* --------------------------------------------------------------------------
 * Where a customer may be sent
 * ----------------------------------------------------------------------- */

/**
 * §9 S5: «Backend возвращает redirect_url на домене platega.io — проверка
 * домена на клиенте обязательна.»
 *
 * The URL arrives from our own backend over TLS, so this is depth rather than
 * a hole being plugged. It is still the cheapest control in the product: the
 * one thing this app does is walk a customer out of Telegram to type card
 * details, and the check that they are typing them at the payment provider
 * costs four lines. Every one of the 30 real payments to date redirected to
 * exactly `pay.platega.io`.
 *
 * Subdomains of platega.io are accepted, anything else is not — including a
 * lookalike like `platega.io.evil.tld`, which is why the test is on the host
 * SUFFIX with a leading dot and not on `includes`.
 */
const PAYMENT_HOSTS = Object.freeze(['platega.io']);

function isAllowedPaymentUrl(url) {
  let u;
  try {
    u = new URL(String(url || ''));
  } catch {
    return false;
  }
  if (u.protocol !== 'https:') return false;
  const host = u.hostname.toLowerCase();

  return PAYMENT_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
}

/**
 * What to call a destination the customer already owns or has ordered.
 *
 * The owned side (`customer_esims`, `retail_orders`) carries `country_code` and
 * `package_name` and NOTHING else — no coverage list, so `isRegional` cannot be
 * asked. Passing the code to `countryLabel` alone was wrong twice over, and
 * both ways were measured against the live catalogue on 2026-08-18:
 *
 *   - 53 of the 59 regional packages file under one arbitrary member country,
 *     so "Best World 10 GB" came out as «Албания» and "LatAm 50 GB" as
 *     «Аргентина». A confident wrong answer is worse than a vague right one.
 *   - 6 packages file under GL-120 / CA-4 / AF-29, which have no Russian name,
 *     and `countryLabel` returns the code itself. RAW CODES = 0 is the rule.
 *
 * The provider's family name is the one thing that distinguishes them, and
 * `regionKey`/`REGION_NAMES` already read it for the catalogue. So the same
 * table answers here — the name is USED, never SHOWN (R10, P3).
 *
 * Order of trust: a known region family, then a known country, then an honest
 * «Регион». The code is never the answer.
 */
function destinationTitle(packageName, countryCode) {
  const named = REGION_NAMES[regionKey({ name: packageName })];
  if (named) return named;

  const key = String(countryCode || '').toUpperCase();
  if (countryNames[key]) return countryNames[key];

  return 'Регион';
}

/* --------------------------------------------------------------------------
 * Status vocabulary — one place, so no screen improvises
 * ----------------------------------------------------------------------- */

const ESIM_STATUS_TEXT = Object.freeze({
  provisioning: 'Выпускается',
  ready: 'Готова к установке',
  active: 'Активна',
  depleted: 'Трафик закончился',
  expired: 'Срок истёк',
  suspended: 'Приостановлена',
  failed: 'Ошибка выпуска',
});

/**
 * Order status, keyed on what the BACKEND actually sends.
 *
 * `display_status` comes from ORDER_DISPLAY_STATUS in lib/tmaProjection.js and
 * its whole vocabulary is: awaiting_payment · paid · provisioning · ready ·
 * failed · canceled · unknown. This table used to be keyed on the internal
 * column instead (`purchasing_esim`, `completed`, `cancelled` with two Ls,
 * `refunded`), so four of seven keys could never match and the two that matter
 * most — «Готовим eSIM» and «eSIM готова» — were unreachable in production.
 *
 * The internal names are kept as aliases rather than deleted: an order row read
 * through some other path still speaks them, and a silent miss here is exactly
 * the failure being fixed.
 */
const ORDER_STATUS_TEXT = Object.freeze({
  awaiting_payment: 'Ждёт оплаты',
  paid: 'Оплачен',
  provisioning: 'Выпускаем eSIM',
  ready: 'Готово',
  failed: 'Не удался',
  canceled: 'Отменён',

  // Aliases — the internal retail_orders.status vocabulary.
  purchasing_esim: 'Выпускаем eSIM',
  completed: 'Готово',
  cancelled: 'Отменён',
  refunded: 'Возврат',
});

/** True for the one display_status that means "the eSIM exists now". */
const isOrderReady = (s) => s === 'ready' || s === 'completed';

/** Terminal and unhappy: nothing will change by waiting. */
const isOrderDead = (s) => s === 'failed' || s === 'canceled'
  || s === 'cancelled' || s === 'refunded';

/**
 * Installation guidance, keyed by the closed activation_policy code.
 *
 * The server maps three known provider sentences to these codes and null to
 * everything else, so this table has a null branch by design: "мы не знаем" is
 * a sentence a customer can act on, and a guess is not.
 */
const ACTIVATION_POLICY_TEXT = Object.freeze({
  ON_FIRST_DATA: 'Срок начнётся с первого использования интернета.',
  ON_NETWORK_ATTACH: 'Срок начнётся, когда телефон подключится к сети за границей.',
  ON_INSTALL: 'Срок начнётся сразу после установки — устанавливайте перед поездкой.',
});

function activationPolicyText(code) {
  return ACTIVATION_POLICY_TEXT[code]
    || 'Уточните момент начала срока в описании тарифа.';
}

/* --------------------------------------------------------------------------
 * Plumbing
 * ----------------------------------------------------------------------- */

function memoryStorage() {
  const m = new Map();

  return {
    getItem: (k) => (m.has(k) ? m.get(k) : null),
    setItem: (k, v) => { m.set(k, String(v)); },
    removeItem: (k) => { m.delete(k); },
  };
}

function defaultRandomHex(bytes) {
  const g = typeof globalThis !== 'undefined' ? globalThis : {};
  if (g.crypto && g.crypto.getRandomValues) {
    const a = new Uint8Array(bytes);
    g.crypto.getRandomValues(a);

    return [...a].map((b) => b.toString(16).padStart(2, '0')).join('');
  }

  // Only reachable in an environment with no WebCrypto. The value is a storage
  // discriminator, not a secret — the idempotency key's job is uniqueness.
  let out = '';
  for (let i = 0; i < bytes * 2; i += 1) out += Math.floor(Math.random() * 16).toString(16);

  return out;
}

const CORE = {
  API_BASE, ApiError, createApi, createCache, readThrough,
  gb, money, daysLeft, remainingFraction,
  purchaseIntentKey, clearIntentKey, hash32,
  byCountry, pickBestValue, searchCountries,
  groupCatalogue, regionsCovering, countryLabel, flagFor, isRegional,
  regionLabel, plural, tariffWord, countryWord,
  normalize, popularGroups, popularCountries, countryLatin,
  ESIM_STATUS_TEXT, ORDER_STATUS_TEXT, activationPolicyText,
  destinationTitle, isOrderReady, isOrderDead,
  isAllowedPaymentUrl, PAYMENT_HOSTS,
  sortOwnedEsims, isSpentEsim, SPENT_ESIM_STATUSES,
  syncedAgo, installPlatform, sortTariffs, TARIFF_SORTS,
  tariffFacts, tariffNetworks, tariffHotspot, tariffActivation, tariffTextRu,
  coverageSummary,
  AFTER_PAYMENT_STEPS,
  memoryStorage,
  READ_ATTEMPTS, WRITE_ATTEMPTS_WITH_KEY, SESSION_ATTEMPTS, REQUEST_TIMEOUT_MS,
  STATIC_CATALOGUE_TIMEOUT_MS,
  API_RENDER, API_GATEWAY, API_ENDPOINTS,
};

if (typeof module !== 'undefined' && module.exports) module.exports = CORE;
if (typeof window !== 'undefined') window.MagicCore = CORE;
