'use strict';

/* ============================================================================
 * Magic eSIM Mini App — the part with no DOM in it.
 *
 * Everything here is testable in Node, and that is the reason it exists as its
 * own file: the interesting behaviour of this app is not layout, it is what
 * happens when the network is unreliable and when a customer taps twice.
 *
 * THREE RULES THIS FILE ENFORCES
 *
 *   1. Reads may be retried. Writes may not — not blindly. A GET that fails
 *      costs a second request; a POST that fails might have succeeded on the
 *      server, and repeating it without an idempotency key is how one tap
 *      becomes two orders. So retry is opt-in per call and the purchase path
 *      carries a key that survives the retry.
 *
 *   2. A single 502 must not look like a broken app. TD-55 (R-38) means the
 *      gateway drops a real share of requests — measured at 20-35% on a bad
 *      minute, with origin healthy throughout. So reads retry with backoff, and
 *      when they still fail the app shows the last good answer with an honest
 *      "shown from cache" rather than an empty screen or an endless spinner.
 *
 *   3. Never invent a number. A usage figure the app could not fetch is
 *      rendered as unknown, never as zero. "0 GB left" and "we could not ask"
 *      look identical in a progress bar and mean opposite things to somebody
 *      standing in an airport.
 * ========================================================================= */

/* --------------------------------------------------------------------------
 * Country names
 *
 * The catalogue DTO carries no name a customer can read: `coverage_countries`
 * is empty on all 973 packages, `name` is English ("Netherlands 3GB 15Days"),
 * and there is no `country` field at all — so the Mini App shipped a country
 * list reading "AD · AE · AF · AF-29 · AG". Blueprint P3 forbids exactly that:
 * the customer never sees an internal technical entity.
 *
 * The names are NOT redefined here. This block is generated from
 * seo/country-names.mjs by seo/build-country-dictionary.mjs — the same source
 * and the same script the storefront uses — and `--check` fails CI if it
 * drifts. Adding this file as a third target is why a new destination can no
 * longer reach the Mini App as a bare ISO code either.
 * ----------------------------------------------------------------------- */

/* --- COUNTRY NAMES ------------------------------------------------------
 * GENERATED by seo/build-country-dictionary.mjs from seo/country-names.mjs.
 * Do not edit by hand: both copies are rewritten from that source, and CI
 * fails when a code in the live catalogue has no name here, so a new
 * destination can no longer reach the storefront as a bare ISO code.
 * --------------------------------------------------------------------- */
const countryNames={
  AD:'Андорра',AE:'ОАЭ',AF:'Афганистан',AG:'Антигуа и Барбуда',AI:'Ангилья',AL:'Албания',
  AM:'Армения',AO:'Ангола',AR:'Аргентина',AS:'Американское Самоа',AT:'Австрия',AU:'Австралия',
  AW:'Аруба',AX:'Аландские острова',AZ:'Азербайджан',BA:'Босния и Герцеговина',BB:'Барбадос',
  BD:'Бангладеш',BE:'Бельгия',BF:'Буркина-Фасо',BG:'Болгария',BH:'Бахрейн',BI:'Бурунди',BJ:'Бенин',
  BL:'Сен-Бартелеми',BM:'Бермуды',BN:'Бруней',BO:'Боливия',BQ:'Бонэйр, Синт-Эстатиус и Саба',
  BR:'Бразилия',BS:'Багамы',BT:'Бутан',BW:'Ботсвана',BY:'Беларусь',BZ:'Белиз',CA:'Канада',
  CD:'ДР Конго',CF:'Центральноафриканская Республика',CG:'Республика Конго',CH:'Швейцария',
  CI:'Кот-д’Ивуар',CK:'Острова Кука',CL:'Чили',CM:'Камерун',CN:'Китай',CO:'Колумбия',
  CR:'Коста-Рика',CU:'Куба',CV:'Кабо-Верде',CW:'Кюрасао',CY:'Кипр',CZ:'Чехия',DE:'Германия',
  DJ:'Джибути',DK:'Дания',DM:'Доминика',DO:'Доминикана',DZ:'Алжир',EC:'Эквадор',EE:'Эстония',
  EG:'Египет',ER:'Эритрея',ES:'Испания',ET:'Эфиопия',FI:'Финляндия',FJ:'Фиджи',
  FK:'Фолклендские острова',FM:'Микронезия',FO:'Фарерские острова',FR:'Франция',GA:'Габон',
  GB:'Великобритания',GD:'Гренада',GE:'Грузия',GF:'Французская Гвиана',GG:'Гернси',GH:'Гана',
  GI:'Гибралтар',GL:'Гренландия',GM:'Гамбия',GN:'Гвинея',GP:'Гваделупа',GQ:'Экваториальная Гвинея',
  GR:'Греция',GT:'Гватемала',GU:'Гуам',GW:'Гвинея-Бисау',GY:'Гайана',HK:'Гонконг',HN:'Гондурас',
  HR:'Хорватия',HT:'Гаити',HU:'Венгрия',ID:'Индонезия',IE:'Ирландия',IL:'Израиль',IM:'Остров Мэн',
  IN:'Индия',IQ:'Ирак',IR:'Иран',IS:'Исландия',IT:'Италия',JE:'Джерси',JM:'Ямайка',JO:'Иордания',
  JP:'Япония',KE:'Кения',KG:'Киргизия',KH:'Камбоджа',KI:'Кирибати',KM:'Коморы',
  KN:'Сент-Китс и Невис',KR:'Южная Корея',KW:'Кувейт',KY:'Каймановы острова',KZ:'Казахстан',
  LA:'Лаос',LB:'Ливан',LC:'Сент-Люсия',LI:'Лихтенштейн',LK:'Шри-Ланка',LR:'Либерия',LS:'Лесото',
  LT:'Литва',LU:'Люксембург',LV:'Латвия',LY:'Ливия',MA:'Марокко',MC:'Монако',MD:'Молдова',
  ME:'Черногория',MF:'Сен-Мартен',MG:'Мадагаскар',MH:'Маршалловы Острова',MK:'Северная Македония',
  ML:'Мали',MM:'Мьянма',MN:'Монголия',MO:'Макао',MP:'Северные Марианские острова',MQ:'Мартиника',
  MR:'Мавритания',MS:'Монтсеррат',MT:'Мальта',MU:'Маврикий',MV:'Мальдивы',MW:'Малави',MX:'Мексика',
  MY:'Малайзия',MZ:'Мозамбик',NA:'Намибия',NC:'Новая Каледония',NE:'Нигер',NG:'Нигерия',
  NI:'Никарагуа',NL:'Нидерланды',NO:'Норвегия',NP:'Непал',NR:'Науру',NU:'Ниуэ',NZ:'Новая Зеландия',
  OM:'Оман',OTHER:'Другие страны',PA:'Панама',PE:'Перу',PF:'Французская Полинезия',
  PG:'Папуа — Новая Гвинея',PH:'Филиппины',PK:'Пакистан',PL:'Польша',PM:'Сен-Пьер и Микелон',
  PR:'Пуэрто-Рико',PS:'Палестина',PT:'Португалия',PW:'Палау',PY:'Парагвай',QA:'Катар',RE:'Реюньон',
  RO:'Румыния',RS:'Сербия',RU:'Россия',RW:'Руанда',SA:'Саудовская Аравия',SB:'Соломоновы Острова',
  SC:'Сейшелы',SD:'Судан',SE:'Швеция',SG:'Сингапур',SI:'Словения',SK:'Словакия',SL:'Сьерра-Леоне',
  SM:'Сан-Марино',SN:'Сенегал',SO:'Сомали',SR:'Суринам',SS:'Южный Судан',ST:'Сан-Томе и Принсипи',
  SV:'Сальвадор',SX:'Синт-Мартен',SY:'Сирия',SZ:'Эсватини',TC:'Теркс и Кайкос',TD:'Чад',TG:'Того',
  TH:'Таиланд',TJ:'Таджикистан',TL:'Восточный Тимор',TM:'Туркменистан',TN:'Тунис',TO:'Тонга',
  TR:'Турция',TT:'Тринидад и Тобаго',TV:'Тувалу',TW:'Тайвань',TZ:'Танзания',UA:'Украина',
  UG:'Уганда',US:'США',UY:'Уругвай',UZ:'Узбекистан',VA:'Ватикан',VC:'Сент-Винсент и Гренадины',
  VE:'Венесуэла',VG:'Британские Виргинские острова',VI:'Виргинские острова США',VN:'Вьетнам',
  VU:'Вануату',WS:'Самоа',XK:'Косово',YE:'Йемен',YT:'Майотта',ZA:'ЮАР',ZM:'Замбия',ZW:'Зимбабве',
};
/* --- END COUNTRY NAMES --- */

/* --------------------------------------------------------------------------
 * Configuration
 * ----------------------------------------------------------------------- */

// The gateway, always. Never the Render origin directly: RU networks reach
// api.magicesim.store 3/3 and the origin 0/3 (measured 2026-08-16), which is the
// entire reason the proxy exists. A "temporary" direct fallback here would be
// invisible in testing and broken for exactly the customers this app is for.
const API_BASE = 'https://api.magicesim.store';

// Reads: three attempts total. The first retry catches a dropped connection, the
// second catches a bad few seconds. A third would mostly add latency to an
// outage a human can already see.
const READ_ATTEMPTS = 3;
const READ_BACKOFF_MS = [400, 1200];

// Writes get ONE retry and only when a key makes it safe to repeat.
const WRITE_ATTEMPTS_WITH_KEY = 2;
const WRITE_BACKOFF_MS = [700];

// The session mint gets a read's budget, because the whole app is blocked behind
// it and a cold gateway reliably burns the first attempt. See openSession.
const SESSION_ATTEMPTS = 3;
const SESSION_BACKOFF_MS = [600, 1500];

// Longer than the gateway's own ~12s retry budget would take to exhaust, so a
// slow-but-alive request is not abandoned by the client first; short enough that
// a hung one does not become a spinner nobody can dismiss.
const REQUEST_TIMEOUT_MS = 20000;

/* --------------------------------------------------------------------------
 * Small helpers
 * ----------------------------------------------------------------------- */

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Bytes -> GB for display. null stays null: unknown is not zero. */
function gb(bytes) {
  if (bytes === null || bytes === undefined || bytes === '') return null;
  const n = Number(bytes);
  if (!Number.isFinite(n) || n < 0) return null;

  return Math.round((n / (1024 ** 3)) * 100) / 100;
}

/**
 * A price for a Russian customer: whole roubles, grouped, sign after.
 *
 * Non-breaking spaces, written as ESCAPES rather than typed. A price that wraps
 * between its digits — or away from its sign — is a price somebody misreads, and
 * a literal space character in source is invisible in review and easy for an
 * editor to normalise into something else. This started life as U+2009 THIN
 * SPACE, which is breakable in some renderers.
 */
function money(rub) {
  // Absence before coercion, for the third time in this file: Number(null) is 0,
  // so a missing price would render as "0 ₽" — a free eSIM, confidently offered.
  if (rub === null || rub === undefined || rub === '') return '';

  const n = Number(rub);
  if (!Number.isFinite(n)) return '';

  const grouped = Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, '\u00A0');

  return `${grouped}\u00A0\u20BD`;
}

/**
 * Days left, floored, never negative.
 *
 * Floored rather than rounded on purpose: telling somebody they have "1 day"
 * when 4 hours remain is the error that gets a customer stranded.
 */
function daysLeft(expiresAt, now = Date.now()) {
  if (!expiresAt) return null;
  const t = new Date(expiresAt).getTime();
  if (!Number.isFinite(t)) return null;

  return Math.max(0, Math.floor((t - now) / 86400000));
}

/**
 * How much of the bundle is left, 0..1, or null when unknown.
 *
 * Returns null — not 0 — when either side is missing, so a progress bar can
 * render "unknown" instead of an empty tank.
 */
function remainingFraction(esim) {
  // `Number(null)` is 0, not NaN — which is exactly how "we could not ask the
  // provider" turns into "you have nothing left". So absence is checked BEFORE
  // coercion, on both sides.
  const rawTotal = esim ? esim.total_gb : null;
  const rawLeft = esim ? esim.remaining_gb : null;
  if (rawTotal === null || rawTotal === undefined || rawTotal === '') return null;
  if (rawLeft === null || rawLeft === undefined || rawLeft === '') return null;

  const total = Number(rawTotal);
  const left = Number(rawLeft);
  if (!Number.isFinite(total) || total <= 0) return null;
  if (!Number.isFinite(left)) return null;

  return Math.max(0, Math.min(1, left / total));
}

/* --------------------------------------------------------------------------
 * Idempotency keys
 * ----------------------------------------------------------------------- */

/**
 * One key per purchase INTENT, not per request.
 *
 * The distinction is the whole mechanism. A double tap, a retry after a timeout
 * and a resumed screen are all the same intent and must carry the same key, or
 * the customer pays twice. Choosing a different tariff is a new intent and must
 * carry a new one, or the second purchase silently replays the first.
 *
 * The key is derived from what identifies the intent and kept in sessionStorage
 * so it survives the Mini App being backgrounded mid-payment — which is exactly
 * what happens, because paying leaves Telegram for a browser and comes back.
 */
function purchaseIntentKey(intent, storage, randomHex) {
  const scope = [
    'buy',
    String((intent && intent.package_id) || ''),
    String((intent && intent.payment_type) || ''),
    String((intent && intent.promo_code) || '').trim().toUpperCase(),
    String((intent && intent.email) || '').trim().toLowerCase(),
  ].join('|');

  const slot = `mesim.idem.${hash32(scope)}`;
  const existing = storage && storage.getItem ? storage.getItem(slot) : null;
  if (existing) return existing;

  const fresh = `tma-${hash32(scope)}-${randomHex(8)}`;
  if (storage && storage.setItem) storage.setItem(slot, fresh);

  return fresh;
}

/** Forget an intent's key, so the next purchase of the same tariff is a new one. */
function clearIntentKey(intent, storage) {
  const scope = [
    'buy',
    String((intent && intent.package_id) || ''),
    String((intent && intent.payment_type) || ''),
    String((intent && intent.promo_code) || '').trim().toUpperCase(),
    String((intent && intent.email) || '').trim().toLowerCase(),
  ].join('|');
  if (storage && storage.removeItem) storage.removeItem(`mesim.idem.${hash32(scope)}`);
}

/** Tiny stable hash. Not security — a storage slot name. */
function hash32(text) {
  let h = 2166136261;
  const s = String(text);
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }

  return (h >>> 0).toString(36);
}

/* --------------------------------------------------------------------------
 * The API client
 * ----------------------------------------------------------------------- */

class ApiError extends Error {
  constructor(status, code, message, body) {
    super(message || code || `HTTP ${status}`);
    this.name = 'ApiError';
    this.status = status;
    this.code = code || '';
    this.body = body || null;
  }

  /** The session is gone and the app must mint a new one from initData. */
  get isAuthFailure() {
    return this.status === 401;
  }

  /**
   * The request never reached a decision — a gateway drop, a timeout, an offline
   * radio. Safe to retry for a read; for a write, only with a key.
   */
  get isTransport() {
    return this.status === 0 || this.status === 502 || this.status === 503 || this.status === 504;
  }
}

/**
 * @param {object} deps
 * @param {Function} deps.fetch      window.fetch, or a stub
 * @param {object}   deps.storage    sessionStorage-like
 * @param {Function} [deps.now]
 * @param {Function} [deps.sleep]
 * @param {Function} [deps.randomHex]
 */
function createApi(deps = {}) {
  const doFetch = deps.fetch;
  const storage = deps.storage || memoryStorage();
  const now = deps.now || (() => Date.now());
  const wait = deps.sleep || sleep;
  const randomHex = deps.randomHex || defaultRandomHex;
  const base = deps.base || API_BASE;

  // Held in memory only. Writing a bearer to localStorage would leave it on the
  // device after the app closes, and it is re-mintable from initData for free.
  let sessionToken = null;
  let sessionExpiresAt = 0;

  async function once(path, { method = 'GET', body = null, auth = true } = {}) {
    const controller = typeof AbortController === 'function' ? new AbortController() : null;
    const timer = controller ? setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS) : null;

    try {
      const res = await doFetch(base + path, {
        method,
        headers: Object.assign(
          { 'Content-Type': 'application/json', Accept: 'application/json' },
          auth && sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}
        ),
        body: body === null ? undefined : JSON.stringify(body),
        signal: controller ? controller.signal : undefined,
      });

      const text = await res.text();
      let json = null;
      try { json = text ? JSON.parse(text) : null; } catch { json = null; }

      if (!res.ok) {
        throw new ApiError(res.status, json && json.error, json && json.message, json);
      }

      return json;
    } catch (err) {
      if (err instanceof ApiError) throw err;
      // A thrown fetch is a transport failure: DNS, TLS, offline, abort. Status 0
      // so `isTransport` treats it like the gateway drop it usually is.
      throw new ApiError(0, 'NETWORK', 'network unavailable', null);
    } finally {
      if (timer) clearTimeout(timer);
    }
  }

  /**
   * One request, with the retry policy the method deserves.
   *
   * A 401 is retried exactly once, after re-authenticating — a 30-minute session
   * expiring while the app sits open is the single most likely failure here, and
   * making the customer notice it would be pointless.
   */
  async function request(path, opts = {}) {
    const isWrite = opts.method && opts.method !== 'GET';
    const retryable = !isWrite || Boolean(opts.idempotent);
    const attempts = isWrite
      ? (opts.idempotent ? WRITE_ATTEMPTS_WITH_KEY : 1)
      : READ_ATTEMPTS;
    const backoff = isWrite ? WRITE_BACKOFF_MS : READ_BACKOFF_MS;

    let lastError = null;
    let reauthed = false;

    for (let attempt = 0; attempt < attempts; attempt += 1) {
      try {
        return await once(path, opts);
      } catch (err) {
        lastError = err;

        if (err.isAuthFailure && !reauthed && opts.auth !== false && deps.reauthenticate) {
          reauthed = true;
          await deps.reauthenticate();
          continue;                      // does not consume an attempt
        }
        if (!err.isTransport || !retryable || attempt === attempts - 1) throw err;

        await wait(backoff[Math.min(attempt, backoff.length - 1)]);
      }
    }

    throw lastError;
  }

  /* ---- session ---- */

  /**
   * Mint a session from initData.
   *
   * This is the one request the entire app waits on, and until 2026-08-17 it was
   * the only one in the file with no retry at all — `once`, one shot. A cold
   * gateway (TD-55) answers the first call after an idle period with a 502 about
   * twelve seconds in; measured 2026-08-17, five of six cold probes did exactly
   * that while the same instance then served 401s in 0.2s. One such 502 killed
   * the Mini App outright: no session, no catalogue, nothing to tap (R-44).
   *
   * Reads get three attempts for weaker reasons. So does this now.
   *
   * Retrying is safe: minting is not a purchase. It writes a session row and
   * touches no order, payment or provider, so the worst case of a retried cold
   * start is two short-lived rows where one was wanted.
   */
  async function openSession(initData) {
    let lastError = null;

    for (let attempt = 0; attempt < SESSION_ATTEMPTS; attempt += 1) {
      try {
        const out = await once('/api/v1/tma/session', {
          method: 'POST', body: { init_data: initData }, auth: false,
        });
        sessionToken = out.session_token;
        sessionExpiresAt = now() + (Number(out.expires_in) || 0) * 1000;

        return out;
      } catch (err) {
        lastError = err;
        // A rejected initData is a verdict, not a blip: 401 and 403 mean the
        // signature did not check out, and asking again cannot change that.
        if (!err.isTransport || attempt === SESSION_ATTEMPTS - 1) throw err;

        await wait(SESSION_BACKOFF_MS[Math.min(attempt, SESSION_BACKOFF_MS.length - 1)]);
      }
    }

    throw lastError;
  }

  const hasSession = () => Boolean(sessionToken) && now() < sessionExpiresAt;

  /* ---- catalogue (public, no session) ---- */

  // The same endpoint the website uses. §8.3 rejected a TMA twin of it, so this
  // is deliberately not a Mini-App-specific catalogue.
  const catalogue = () => request('/api/v1/retail/packages', { auth: false });

  /* ---- the customer's own things ---- */

  const me = () => request('/api/v1/tma/me');
  const orders = (params = '') => request(`/api/v1/tma/me/orders${params}`);
  const activeOrders = () => request('/api/v1/tma/me/orders/active');
  const orderStatus = (token) => request(`/api/v1/tma/orders/${encodeURIComponent(token)}/status`);
  const esims = () => request('/api/v1/tma/esims');
  const esim = (id) => request(`/api/v1/tma/esims/${encodeURIComponent(id)}`);

  // POST, but it creates nothing — see the route comment. Retryable as a read is
  // wrong (it is a POST), so it gets the write policy without a key: one shot.
  const activation = (id) => request(
    `/api/v1/tma/esims/${encodeURIComponent(id)}/activation`, { method: 'POST', body: {} }
  );

  const refreshUsage = (id) => request(
    `/api/v1/tma/esims/${encodeURIComponent(id)}/usage/refresh`, { method: 'POST', body: {} }
  );

  /**
   * Buy. The only call in this file that can spend money.
   *
   * `idempotent: true` is what makes the single retry safe, and the key comes
   * from the INTENT rather than from this call — so a retry, a double tap and a
   * resumed screen all reuse it.
   */
  async function purchase(intent) {
    const key = purchaseIntentKey(intent, storage, randomHex);

    return request('/api/v1/tma/orders', {
      method: 'POST',
      idempotent: true,
      body: {
        package_id: intent.package_id,
        email: intent.email,
        payment_type: intent.payment_type,
        // Reported, never asserted. This was hardcoded `true`, which sent an
        // acceptance the customer had not given — §9 S4 and §14.6 both require
        // an explicit act, and a pre-ticked box is expressly not one. The
        // checkout will not enable its pay button until the box is ticked, so a
        // false here means something went wrong and the server should refuse.
        terms_accepted: intent.terms_accepted === true,
        promo_code: intent.promo_code || undefined,
        // An assertion about what was shown, never an instruction. The server
        // prices the order and refuses if this disagrees.
        expected_amount_rub: intent.expected_amount_rub,
        idempotency_key: key,
      },
    });
  }

  return {
    openSession, hasSession, catalogue, me, orders, activeOrders, orderStatus,
    esims, esim, activation, refreshUsage, purchase,
    forgetIntent: (intent) => clearIntentKey(intent, storage),
    get token() { return sessionToken; },
  };
}

/* --------------------------------------------------------------------------
 * A read-through cache that is honest about staleness
 * ----------------------------------------------------------------------- */

/**
 * Serve the last good answer when the network will not cooperate.
 *
 * This is the concrete answer to TD-55 in the UI: a customer who opens "my
 * eSIMs" on a bad minute sees their eSIMs with a quiet "shown from cache" line,
 * not an error and not a spinner. What it must never do is hide a failure on a
 * WRITE, so only reads go through here.
 */
function createCache(storage, { now = () => Date.now() } = {}) {
  const KEY = (name) => `mesim.cache.${name}`;

  return {
    read(name, maxAgeMs) {
      try {
        const raw = storage.getItem(KEY(name));
        if (!raw) return null;
        const parsed = JSON.parse(raw);
        const age = now() - Number(parsed.at || 0);
        if (maxAgeMs && age > maxAgeMs) return { value: parsed.value, age, expired: true };

        return { value: parsed.value, age, expired: false };
      } catch {
        return null;
      }
    },
    write(name, value) {
      try {
        storage.setItem(KEY(name), JSON.stringify({ at: now(), value }));
      } catch {
        // A full or disabled storage must not break the app. Losing the cache
        // costs a spinner; throwing here costs the screen.
      }
    },
  };
}

/**
 * Fetch, and fall back to cache with the staleness made visible.
 *
 * Returns { value, stale, error } so a caller cannot accidentally present cached
 * data as fresh — the flag is in the same object as the data.
 */
async function readThrough(cache, name, fetcher) {
  try {
    const value = await fetcher();
    cache.write(name, value);

    return { value, stale: false, error: null };
  } catch (err) {
    const cached = cache.read(name);
    if (cached) return { value: cached.value, stale: true, error: err, age: cached.age };

    return { value: null, stale: false, error: err };
  }
}

/* --------------------------------------------------------------------------
 * Catalogue shaping — done here so the UI stays dumb
 * ----------------------------------------------------------------------- */

/**
 * Group the flat package list by country, and pick a "best value" per country.
 *
 * Best value is cheapest-per-GB among the cheapest half, not simply the cheapest
 * plan: the 1 GB option is almost always cheapest and almost never what somebody
 * travelling for a week wants.
 */
/**
 * Russian names for the multi-country families the provider ships.
 *
 * These are NOT countries and have no ISO code, so they cannot come from the
 * generated dictionary: three arrive with invented codes (`AF-29`, `CA-4`,
 * `GL-120`) and the rest are filed under whichever member country sorts first,
 * which is why "Vietnam Plus" was shelved under Indonesia. Keyed on the English
 * family name because that is the stable part of the provider's title — the
 * volume and duration suffix varies per package.
 *
 * A family missing here falls back to naming itself by its coverage ("Регион ·
 * 6 стран"), which is honest rather than technical. It never shows the code.
 */
const REGION_NAMES = Object.freeze({
  'EU': 'Европа',
  'EUCONNECT': 'Европа',
  'EUROPE AND USA': 'Европа и США',
  'AFRICA': 'Африка',
  'CARIBBEAN': 'Карибские острова',
  'BEST WORLD': 'Весь мир',
  'HALF GLOBAL': 'Полмира',
  'GLOBAL': 'Весь мир',
  'LATAM': 'Латинская Америка',
  'APAC': 'Азия и Океания',
  'AUSTRALIA AND NZ': 'Австралия и Новая Зеландия',
  'CENTRAL ASIA': 'Центральная Азия',
  'CHINA KOREA JAPAN': 'Китай, Корея и Япония',
  'GREATER CHINA AND TAIWAN PREMIUM': 'Большой Китай и Тайвань',
  'GREECE CYPRUS TURKEY': 'Греция, Кипр и Турция',
  'JERSEY GUERNSEY AND IOM': 'Джерси, Гернси и Мэн',
  'VIETNAM PLUS': 'Вьетнам и Юго-Восточная Азия',
  'SINGAPORE MALAYSIA AND THAILAND': 'Сингапур, Малайзия и Таиланд',
  'SPAIN AND PORTUGAL': 'Испания и Португалия',
  'ITALY': 'Италия',
});

/** Russian country name, or the code if we somehow have none. Never blank. */
function countryLabel(code) {
  const key = String(code || '').toUpperCase();
  return countryNames[key] || key;
}

/** The flag the catalogue already carries, or one derived from the ISO code. */
function flagFor(code, pkg) {
  if (pkg && pkg.coverage_flags && String(pkg.coverage_flags).trim()) {
    // Regional packages carry a whole string of them; one flag is a label, ten
    // are noise on a 375px screen.
    const flags = [...String(pkg.coverage_flags).trim()];
    if (flags.length <= 4) return String(pkg.coverage_flags).trim();
  }
  const key = String(code || '').toUpperCase();
  if (!/^[A-Z]{2}$/.test(key)) return '';

  return key.replace(/[A-Z]/g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

/** A package covering more than one country is a regional offer, not a local one. */
function isRegional(pkg) {
  return Array.isArray(pkg && pkg.coverage_country_codes) && pkg.coverage_country_codes.length > 1;
}

/** "3 тарифа" — Russian needs three forms and "1 тарифов" reads as a bug. */
function plural(n, one, few, many) {
  const abs = Math.abs(Number(n) || 0);
  const mod10 = abs % 10;
  const mod100 = abs % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;

  return many;
}

const tariffWord = (n) => `${n} ${plural(n, 'тариф', 'тарифа', 'тарифов')}`;
const countryWord = (n) => `${n} ${plural(n, 'страна', 'страны', 'стран')}`;

/** The provider's family name, normalised to a REGION_NAMES key. */
function regionKey(pkg) {
  return String((pkg && pkg.name) || '')
    .replace(/\s*\d+\s*GB[\s\S]*$/i, '')     // "Africa 5GB 30Days" -> "Africa"
    .replace(/\s*\(\d+\+?\s*areas?\)/i, '')  // "Global (120+ areas)" -> "Global"
    .replace(/\s+Unlimited[\s\S]*$/i, '')    // "EUconnect Unlimited 7 Days" -> "EUconnect"
    .replace(/\s+Premium$/i, ' Premium')
    .trim()
    .toUpperCase();
}

function regionLabel(pkg) {
  const named = REGION_NAMES[regionKey(pkg)];
  if (named) return named;
  const n = (pkg && pkg.coverage_country_codes && pkg.coverage_country_codes.length) || 0;

  return n ? `Регион · ${countryWord(n)}` : 'Регион';
}

function byCountry(packages) {
  const map = new Map();
  for (const p of (Array.isArray(packages) ? packages : [])) {
    // A catalogue is external input. One malformed row must cost that row, not
    // the screen.
    if (!p || typeof p !== 'object') continue;
    const code = String(p.country_code || '').toUpperCase();
    if (!code) continue;
    if (!map.has(code)) {
      map.set(code, {
        country_code: code,
        country: countryLabel(code),
        flag: flagFor(code, p),
        items: [],
      });
    }
    map.get(code).items.push(p);
  }

  for (const group of map.values()) {
    group.items.sort((a, b) => Number(a.price) - Number(b.price));
    group.from = group.items.length ? Number(group.items[0].price) : null;
    group.best = pickBestValue(group.items);
  }

  return [...map.values()].sort((a, b) => String(a.country).localeCompare(String(b.country), 'ru'));
}

/**
 * S1's data model: local destinations and regional offers are different things
 * and the Blueprint lists them as separate sections (§9 S1, items 4 and 5).
 *
 * Splitting them also fixes a lie the flat grouping told. A regional package is
 * filed under one member country, so "Vietnam Plus" — six countries — appeared
 * as an Indonesian tariff, and "EU" (34 countries) as an Andorran one.
 */
function groupCatalogue(packages) {
  const rows = (Array.isArray(packages) ? packages : []).filter((p) => p && typeof p === 'object');
  const local = rows.filter((p) => !isRegional(p));
  const wide = rows.filter(isRegional);

  const regions = new Map();
  for (const p of wide) {
    const label = regionLabel(p);
    if (!regions.has(label)) {
      regions.set(label, {
        country_code: String(p.country_code || '').toUpperCase(),
        country: label,
        // A handful of flags still reads as a place; twenty-nine of them is a
        // smear, and a globe says "region" better than a truncated list.
        flag: (p.coverage_country_codes || []).length <= 3
          ? flagFor(p.country_code, p)
          : '🌍',
        regional: true,
        coverage: (p.coverage_country_codes || []).slice(),
        items: [],
      });
    }
    const g = regions.get(label);
    g.items.push(p);
    // Keep the widest coverage we have seen for this family: the customer is
    // choosing a region, and the honest count is the biggest one it sells.
    if ((p.coverage_country_codes || []).length > g.coverage.length) {
      g.coverage = p.coverage_country_codes.slice();
    }
  }

  const finish = (g) => {
    g.items.sort((a, b) => Number(a.price) - Number(b.price));
    g.from = g.items.length ? Number(g.items[0].price) : null;
    g.best = pickBestValue(g.items);

    return g;
  };

  return {
    countries: byCountry(local),
    regions: [...regions.values()].map(finish)
      .sort((a, b) => (b.coverage.length - a.coverage.length)),
  };
}

/**
 * Regional offers that cover a given country.
 *
 * Blueprint §9 S2: a country with no local tariff is "не ошибка, а тупик, из
 * которого нужен выход" — and even where local tariffs exist, a traveller
 * crossing borders is better served by knowing the regional one exists.
 */
function regionsCovering(regions, code) {
  const key = String(code || '').toUpperCase();

  return (regions || [])
    .filter((r) => (r.coverage || []).some((c) => String(c).toUpperCase() === key))
    .sort((a, b) => Number(a.from) - Number(b.from));
}

function pickBestValue(items) {
  const usable = (items || []).filter((p) => Number(p.data_gb) > 0 && Number(p.price) > 0);
  if (!usable.length) return null;
  const scored = usable
    .map((p) => ({ p, perGb: Number(p.price) / Number(p.data_gb) }))
    .sort((a, b) => a.perGb - b.perGb);

  return scored[0].p;
}

/** Free-text country search that tolerates the way people actually type. */
function searchCountries(groups, query) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return groups;

  return groups.filter((g) => String(g.country).toLowerCase().includes(q)
    || String(g.country_code).toLowerCase().startsWith(q));
}

/* --------------------------------------------------------------------------
 * Status vocabulary — one place, so no screen improvises
 * ----------------------------------------------------------------------- */

const ESIM_STATUS_TEXT = Object.freeze({
  provisioning: 'Выпускается',
  ready: 'Готова к установке',
  active: 'Активна',
  depleted: 'Трафик закончился',
  expired: 'Срок истёк',
  suspended: 'Приостановлена',
  failed: 'Ошибка выпуска',
});

const ORDER_STATUS_TEXT = Object.freeze({
  awaiting_payment: 'Ждёт оплаты',
  paid: 'Оплачен',
  purchasing_esim: 'Выпускаем eSIM',
  completed: 'Готово',
  failed: 'Не удался',
  cancelled: 'Отменён',
  refunded: 'Возврат',
});

/**
 * Installation guidance, keyed by the closed activation_policy code.
 *
 * The server maps three known provider sentences to these codes and null to
 * everything else, so this table has a null branch by design: "мы не знаем" is
 * a sentence a customer can act on, and a guess is not.
 */
const ACTIVATION_POLICY_TEXT = Object.freeze({
  ON_FIRST_DATA: 'Срок начнётся с первого использования интернета.',
  ON_NETWORK_ATTACH: 'Срок начнётся, когда телефон подключится к сети за границей.',
  ON_INSTALL: 'Срок начнётся сразу после установки — устанавливайте перед поездкой.',
});

function activationPolicyText(code) {
  return ACTIVATION_POLICY_TEXT[code]
    || 'Уточните момент начала срока в описании тарифа.';
}

/* --------------------------------------------------------------------------
 * Plumbing
 * ----------------------------------------------------------------------- */

function memoryStorage() {
  const m = new Map();

  return {
    getItem: (k) => (m.has(k) ? m.get(k) : null),
    setItem: (k, v) => { m.set(k, String(v)); },
    removeItem: (k) => { m.delete(k); },
  };
}

function defaultRandomHex(bytes) {
  const g = typeof globalThis !== 'undefined' ? globalThis : {};
  if (g.crypto && g.crypto.getRandomValues) {
    const a = new Uint8Array(bytes);
    g.crypto.getRandomValues(a);

    return [...a].map((b) => b.toString(16).padStart(2, '0')).join('');
  }

  // Only reachable in an environment with no WebCrypto. The value is a storage
  // discriminator, not a secret — the idempotency key's job is uniqueness.
  let out = '';
  for (let i = 0; i < bytes * 2; i += 1) out += Math.floor(Math.random() * 16).toString(16);

  return out;
}

const CORE = {
  API_BASE, ApiError, createApi, createCache, readThrough,
  gb, money, daysLeft, remainingFraction,
  purchaseIntentKey, clearIntentKey, hash32,
  byCountry, pickBestValue, searchCountries,
  groupCatalogue, regionsCovering, countryLabel, flagFor, isRegional,
  regionLabel, plural, tariffWord, countryWord,
  ESIM_STATUS_TEXT, ORDER_STATUS_TEXT, activationPolicyText,
  memoryStorage,
  READ_ATTEMPTS, WRITE_ATTEMPTS_WITH_KEY, SESSION_ATTEMPTS, REQUEST_TIMEOUT_MS,
};

if (typeof module !== 'undefined' && module.exports) module.exports = CORE;
if (typeof window !== 'undefined') window.MagicCore = CORE;
